//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace Altask.www {
    public partial class SignalRHub {
		internal static void NotifyAssetLogResolutionCreate(Guid? clientId, Altask.Data.Dto.AssetLogResolution assetLogResolution) {
			if (!clientId.HasValue) {
				_context.Clients.All.notifyAssetLogResolutionCreate(new { assetLogResolution = assetLogResolution });
			} else {
				SignalRConnection connection;

				if (_connections.TryGetValue(clientId.Value, out connection)) {
					_context.Clients.AllExcept(connection.ConnectionId).notifyAssetLogResolutionCreate(new { connection = connection, assetLogResolution = assetLogResolution });
				} else {
					_context.Clients.All.notifyAssetLogResolutionCreate(new { assetLogResolution = assetLogResolution });
				}
			}
		}

        internal static void NotifyAssetLogResolutionUpdate(Guid? clientId, Altask.Data.Dto.AssetLogResolution assetLogResolution) {
            if (!clientId.HasValue) {
				_context.Clients.All.notifyAssetLogResolutionUpdate(new { assetLogResolution = assetLogResolution });
			} else {
				SignalRConnection connection;

				if (_connections.TryGetValue(clientId.Value, out connection)) {
					_context.Clients.AllExcept(connection.ConnectionId).notifyAssetLogResolutionUpdate(new { connection = connection, assetLogResolution = assetLogResolution });
				} else {
					_context.Clients.All.notifyAssetLogResolutionCreate(new { assetLogResolution = assetLogResolution });
				}
			}
		}
	}
}
