//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace Altask.www {
    public partial class SignalRHub {
		internal static void NotifyAssetLogTypeCategoryCreate(Guid? clientId, Altask.Data.Dto.AssetLogTypeCategory assetLogTypeCategory) {
			if (!clientId.HasValue) {
				_context.Clients.All.notifyAssetLogTypeCategoryCreate(new { assetLogTypeCategory = assetLogTypeCategory });
			} else {
				SignalRConnection connection;

				if (_connections.TryGetValue(clientId.Value, out connection)) {
					_context.Clients.AllExcept(connection.ConnectionId).notifyAssetLogTypeCategoryCreate(new { connection = connection, assetLogTypeCategory = assetLogTypeCategory });
				} else {
					_context.Clients.All.notifyAssetLogTypeCategoryCreate(new { assetLogTypeCategory = assetLogTypeCategory });
				}
			}
		}

        internal static void NotifyAssetLogTypeCategoryUpdate(Guid? clientId, Altask.Data.Dto.AssetLogTypeCategory assetLogTypeCategory) {
            if (!clientId.HasValue) {
				_context.Clients.All.notifyAssetLogTypeCategoryUpdate(new { assetLogTypeCategory = assetLogTypeCategory });
			} else {
				SignalRConnection connection;

				if (_connections.TryGetValue(clientId.Value, out connection)) {
					_context.Clients.AllExcept(connection.ConnectionId).notifyAssetLogTypeCategoryUpdate(new { connection = connection, assetLogTypeCategory = assetLogTypeCategory });
				} else {
					_context.Clients.All.notifyAssetLogTypeCategoryCreate(new { assetLogTypeCategory = assetLogTypeCategory });
				}
			}
		}
	}
}
