//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace Altask.www {
    public partial class SignalRHub {
		internal static void NotifyScheduleLogCreate(Guid? clientId, Altask.Data.Dto.ScheduleLog scheduleLog) {
			if (!clientId.HasValue) {
				_context.Clients.All.notifyScheduleLogCreate(new { scheduleLog = scheduleLog });
			} else {
				SignalRConnection connection;

				if (_connections.TryGetValue(clientId.Value, out connection)) {
					_context.Clients.AllExcept(connection.ConnectionId).notifyScheduleLogCreate(new { connection = connection, scheduleLog = scheduleLog });
				} else {
					_context.Clients.All.notifyScheduleLogCreate(new { scheduleLog = scheduleLog });
				}
			}
		}

        internal static void NotifyScheduleLogUpdate(Guid? clientId, Altask.Data.Dto.ScheduleLog scheduleLog) {
            if (!clientId.HasValue) {
				_context.Clients.All.notifyScheduleLogUpdate(new { scheduleLog = scheduleLog });
			} else {
				SignalRConnection connection;

				if (_connections.TryGetValue(clientId.Value, out connection)) {
					_context.Clients.AllExcept(connection.ConnectionId).notifyScheduleLogUpdate(new { connection = connection, scheduleLog = scheduleLog });
				} else {
					_context.Clients.All.notifyScheduleLogCreate(new { scheduleLog = scheduleLog });
				}
			}
		}
	}
}
