//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace Altask.www {
    public partial class SignalRHub {
		internal static void NotifyScheduleCreate(Guid? clientId, Altask.Data.Dto.Schedule schedule) {
			if (!clientId.HasValue) {
				_context.Clients.All.notifyScheduleCreate(new { schedule = schedule });
			} else {
				SignalRConnection connection;

				if (_connections.TryGetValue(clientId.Value, out connection)) {
					_context.Clients.AllExcept(connection.ConnectionId).notifyScheduleCreate(new { connection = connection, schedule = schedule });
				} else {
					_context.Clients.All.notifyScheduleCreate(new { schedule = schedule });
				}
			}
		}

        internal static void NotifyScheduleUpdate(Guid? clientId, Altask.Data.Dto.Schedule schedule) {
            if (!clientId.HasValue) {
				_context.Clients.All.notifyScheduleUpdate(new { schedule = schedule });
			} else {
				SignalRConnection connection;

				if (_connections.TryGetValue(clientId.Value, out connection)) {
					_context.Clients.AllExcept(connection.ConnectionId).notifyScheduleUpdate(new { connection = connection, schedule = schedule });
				} else {
					_context.Clients.All.notifyScheduleCreate(new { schedule = schedule });
				}
			}
		}
	}
}
