//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace Altask.www {
    public partial class SignalRHub {
		internal static void NotifyTaskAlertLogCreate(Guid? clientId, Altask.Data.Dto.TaskAlertLog taskAlertLog) {
			if (!clientId.HasValue) {
				_context.Clients.All.notifyTaskAlertLogCreate(new { taskAlertLog = taskAlertLog });
			} else {
				SignalRConnection connection;

				if (_connections.TryGetValue(clientId.Value, out connection)) {
					_context.Clients.AllExcept(connection.ConnectionId).notifyTaskAlertLogCreate(new { connection = connection, taskAlertLog = taskAlertLog });
				} else {
					_context.Clients.All.notifyTaskAlertLogCreate(new { taskAlertLog = taskAlertLog });
				}
			}
		}

        internal static void NotifyTaskAlertLogUpdate(Guid? clientId, Altask.Data.Dto.TaskAlertLog taskAlertLog) {
            if (!clientId.HasValue) {
				_context.Clients.All.notifyTaskAlertLogUpdate(new { taskAlertLog = taskAlertLog });
			} else {
				SignalRConnection connection;

				if (_connections.TryGetValue(clientId.Value, out connection)) {
					_context.Clients.AllExcept(connection.ConnectionId).notifyTaskAlertLogUpdate(new { connection = connection, taskAlertLog = taskAlertLog });
				} else {
					_context.Clients.All.notifyTaskAlertLogCreate(new { taskAlertLog = taskAlertLog });
				}
			}
		}
	}
}
