//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace Altask.www {
    public partial class SignalRHub {
		internal static void NotifyFormCreate(Guid? clientId, Altask.Data.Dto.Form form) {
			if (!clientId.HasValue) {
				_context.Clients.All.notifyFormCreate(new { form = form });
			} else {
				SignalRConnection connection;

				if (_connections.TryGetValue(clientId.Value, out connection)) {
					_context.Clients.AllExcept(connection.ConnectionId).notifyFormCreate(new { connection = connection, form = form });
				} else {
					_context.Clients.All.notifyFormCreate(new { form = form });
				}
			}
		}

        internal static void NotifyFormUpdate(Guid? clientId, Altask.Data.Dto.Form form) {
            if (!clientId.HasValue) {
				_context.Clients.All.notifyFormUpdate(new { form = form });
			} else {
				SignalRConnection connection;

				if (_connections.TryGetValue(clientId.Value, out connection)) {
					_context.Clients.AllExcept(connection.ConnectionId).notifyFormUpdate(new { connection = connection, form = form });
				} else {
					_context.Clients.All.notifyFormCreate(new { form = form });
				}
			}
		}
	}
}
