//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace Altask.www {
    public partial class SignalRHub {
		internal static void NotifyAssetLogCreate(Guid? clientId, Altask.Data.Dto.AssetLog assetLog) {
			if (!clientId.HasValue) {
				_context.Clients.All.notifyAssetLogCreate(new { assetLog = assetLog });
			} else {
				SignalRConnection connection;

				if (_connections.TryGetValue(clientId.Value, out connection)) {
					_context.Clients.AllExcept(connection.ConnectionId).notifyAssetLogCreate(new { connection = connection, assetLog = assetLog });
				} else {
					_context.Clients.All.notifyAssetLogCreate(new { assetLog = assetLog });
				}
			}
		}

        internal static void NotifyAssetLogUpdate(Guid? clientId, Altask.Data.Dto.AssetLog assetLog) {
            if (!clientId.HasValue) {
				_context.Clients.All.notifyAssetLogUpdate(new { assetLog = assetLog });
			} else {
				SignalRConnection connection;

				if (_connections.TryGetValue(clientId.Value, out connection)) {
					_context.Clients.AllExcept(connection.ConnectionId).notifyAssetLogUpdate(new { connection = connection, assetLog = assetLog });
				} else {
					_context.Clients.All.notifyAssetLogCreate(new { assetLog = assetLog });
				}
			}
		}
	}
}
