//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace Altask.www {
    public partial class SignalRHub {
		internal static void NotifyAssetAlertLogCreate(Guid? clientId, Altask.Data.Dto.AssetAlertLog assetAlertLog) {
			if (!clientId.HasValue) {
				_context.Clients.All.notifyAssetAlertLogCreate(new { assetAlertLog = assetAlertLog });
			} else {
				SignalRConnection connection;

				if (_connections.TryGetValue(clientId.Value, out connection)) {
					_context.Clients.AllExcept(connection.ConnectionId).notifyAssetAlertLogCreate(new { connection = connection, assetAlertLog = assetAlertLog });
				} else {
					_context.Clients.All.notifyAssetAlertLogCreate(new { assetAlertLog = assetAlertLog });
				}
			}
		}

        internal static void NotifyAssetAlertLogUpdate(Guid? clientId, Altask.Data.Dto.AssetAlertLog assetAlertLog) {
            if (!clientId.HasValue) {
				_context.Clients.All.notifyAssetAlertLogUpdate(new { assetAlertLog = assetAlertLog });
			} else {
				SignalRConnection connection;

				if (_connections.TryGetValue(clientId.Value, out connection)) {
					_context.Clients.AllExcept(connection.ConnectionId).notifyAssetAlertLogUpdate(new { connection = connection, assetAlertLog = assetAlertLog });
				} else {
					_context.Clients.All.notifyAssetAlertLogCreate(new { assetAlertLog = assetAlertLog });
				}
			}
		}
	}
}
