//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace Altask.www {
    public partial class SignalRHub {
		internal static void NotifyAssetGroupingCreate(Guid? clientId, Altask.Data.Dto.AssetGrouping assetGrouping) {
			if (!clientId.HasValue) {
				_context.Clients.All.notifyAssetGroupingCreate(new { assetGrouping = assetGrouping });
			} else {
				SignalRConnection connection;

				if (_connections.TryGetValue(clientId.Value, out connection)) {
					_context.Clients.AllExcept(connection.ConnectionId).notifyAssetGroupingCreate(new { connection = connection, assetGrouping = assetGrouping });
				} else {
					_context.Clients.All.notifyAssetGroupingCreate(new { assetGrouping = assetGrouping });
				}
			}
		}

        internal static void NotifyAssetGroupingUpdate(Guid? clientId, Altask.Data.Dto.AssetGrouping assetGrouping) {
            if (!clientId.HasValue) {
				_context.Clients.All.notifyAssetGroupingUpdate(new { assetGrouping = assetGrouping });
			} else {
				SignalRConnection connection;

				if (_connections.TryGetValue(clientId.Value, out connection)) {
					_context.Clients.AllExcept(connection.ConnectionId).notifyAssetGroupingUpdate(new { connection = connection, assetGrouping = assetGrouping });
				} else {
					_context.Clients.All.notifyAssetGroupingCreate(new { assetGrouping = assetGrouping });
				}
			}
		}
	}
}
