//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

export class AssetTypeService {
	constructor(AppConfig, CrudService, Logger) {
        this.AppConfig = AppConfig;
        this.CrudService = CrudService;
        this.Logger = Logger
    }

	create(assetType) {
		this.Logger.debug('AssetTypeService.create');
		return this.CrudService.create('AssetType', assetType);
    }

	list(filter) {
		this.Logger.debug('AssetTypeService.list');
        return this.CrudService.list('AssetType', filter);
    }

	update(assetType) {
		this.Logger.debug('AssetTypeService.update');
        return this.CrudService.update('AssetType', assetType);
    }
}

AssetTypeService.$inject = ['AppConfig', 'CrudService', 'Logger'];
