//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

export class AssetService {
	constructor(AppConfig, CrudService, Logger) {
        this.AppConfig = AppConfig;
        this.CrudService = CrudService;
        this.Logger = Logger
    }

	create(asset) {
		this.Logger.debug('AssetService.create');
		return this.CrudService.create('Asset', asset);
    }

	list(filter) {
		this.Logger.debug('AssetService.list');
        return this.CrudService.list('Asset', filter);
    }

	update(asset) {
		this.Logger.debug('AssetService.update');
        return this.CrudService.update('Asset', asset);
    }
}

AssetService.$inject = ['AppConfig', 'CrudService', 'Logger'];
