//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

export class AssetGroupingService {
	constructor(AppConfig, CrudService, Logger) {
        this.AppConfig = AppConfig;
        this.CrudService = CrudService;
        this.Logger = Logger
    }

	create(assetGrouping) {
		this.Logger.debug('AssetGroupingService.create');
		return this.CrudService.create('AssetGrouping', assetGrouping);
    }

	list(filter) {
		this.Logger.debug('AssetGroupingService.list');
        return this.CrudService.list('AssetGrouping', filter);
    }

	update(assetGrouping) {
		this.Logger.debug('AssetGroupingService.update');
        return this.CrudService.update('AssetGrouping', assetGrouping);
    }
}

AssetGroupingService.$inject = ['AppConfig', 'CrudService', 'Logger'];
