//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

export class AssetGroupService {
	constructor(AppConfig, CrudService, Logger) {
        this.AppConfig = AppConfig;
        this.CrudService = CrudService;
        this.Logger = Logger
    }

	create(assetGroup) {
		this.Logger.debug('AssetGroupService.create');
		return this.CrudService.create('AssetGroup', assetGroup);
    }

	list(filter) {
		this.Logger.debug('AssetGroupService.list');
        return this.CrudService.list('AssetGroup', filter);
    }

	update(assetGroup) {
		this.Logger.debug('AssetGroupService.update');
        return this.CrudService.update('AssetGroup', assetGroup);
    }
}

AssetGroupService.$inject = ['AppConfig', 'CrudService', 'Logger'];
