//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

export class AssetLogTypeService {
	constructor(AppConfig, CrudService, Logger) {
        this.AppConfig = AppConfig;
        this.CrudService = CrudService;
        this.Logger = Logger
    }

	create(assetLogType) {
		this.Logger.debug('AssetLogTypeService.create');
		return this.CrudService.create('AssetLogType', assetLogType);
    }

	list(filter) {
		this.Logger.debug('AssetLogTypeService.list');
        return this.CrudService.list('AssetLogType', filter);
    }

	update(assetLogType) {
		this.Logger.debug('AssetLogTypeService.update');
        return this.CrudService.update('AssetLogType', assetLogType);
    }
}

AssetLogTypeService.$inject = ['AppConfig', 'CrudService', 'Logger'];
