//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

export class AssetAlertUserService {
	constructor(AppConfig, CrudService, Logger) {
        this.AppConfig = AppConfig;
        this.CrudService = CrudService;
        this.Logger = Logger
    }

	create(assetAlertUser) {
		this.Logger.debug('AssetAlertUserService.create');
		return this.CrudService.create('AssetAlertUser', assetAlertUser);
    }

	list(filter) {
		this.Logger.debug('AssetAlertUserService.list');
        return this.CrudService.list('AssetAlertUser', filter);
    }

	update(assetAlertUser) {
		this.Logger.debug('AssetAlertUserService.update');
        return this.CrudService.update('AssetAlertUser', assetAlertUser);
    }
}

AssetAlertUserService.$inject = ['AppConfig', 'CrudService', 'Logger'];
