//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

export class DepartmentService {
	constructor(AppConfig, CrudService, Logger) {
        this.AppConfig = AppConfig;
        this.CrudService = CrudService;
        this.Logger = Logger
    }

	create(department) {
		this.Logger.debug('DepartmentService.create');
		return this.CrudService.create('Department', department);
    }

	list(filter) {
		this.Logger.debug('DepartmentService.list');
        return this.CrudService.list('Department', filter);
    }

	update(department) {
		this.Logger.debug('DepartmentService.update');
        return this.CrudService.update('Department', department);
    }
}

DepartmentService.$inject = ['AppConfig', 'CrudService', 'Logger'];
