//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

export class FormService {
	constructor(AppConfig, CrudService, Logger) {
        this.AppConfig = AppConfig;
        this.CrudService = CrudService;
        this.Logger = Logger
    }

	create(form) {
		this.Logger.debug('FormService.create');
		return this.CrudService.create('Form', form);
    }

	list(filter) {
		this.Logger.debug('FormService.list');
        return this.CrudService.list('Form', filter);
    }

	update(form) {
		this.Logger.debug('FormService.update');
        return this.CrudService.update('Form', form);
    }
}

FormService.$inject = ['AppConfig', 'CrudService', 'Logger'];
