//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

export class ScheduleUserService {
	constructor(AppConfig, CrudService, Logger) {
        this.AppConfig = AppConfig;
        this.CrudService = CrudService;
        this.Logger = Logger
    }

	create(scheduleUser) {
		this.Logger.debug('ScheduleUserService.create');
		return this.CrudService.create('ScheduleUser', scheduleUser);
    }

	list(filter) {
		this.Logger.debug('ScheduleUserService.list');
        return this.CrudService.list('ScheduleUser', filter);
    }

	update(scheduleUser) {
		this.Logger.debug('ScheduleUserService.update');
        return this.CrudService.update('ScheduleUser', scheduleUser);
    }
}

ScheduleUserService.$inject = ['AppConfig', 'CrudService', 'Logger'];
