//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

export class ScheduleAssetTypeService {
	constructor(AppConfig, CrudService, Logger) {
        this.AppConfig = AppConfig;
        this.CrudService = CrudService;
        this.Logger = Logger
    }

	create(scheduleAssetType) {
		this.Logger.debug('ScheduleAssetTypeService.create');
		return this.CrudService.create('ScheduleAssetType', scheduleAssetType);
    }

	list(filter) {
		this.Logger.debug('ScheduleAssetTypeService.list');
        return this.CrudService.list('ScheduleAssetType', filter);
    }

	update(scheduleAssetType) {
		this.Logger.debug('ScheduleAssetTypeService.update');
        return this.CrudService.update('ScheduleAssetType', scheduleAssetType);
    }
}

ScheduleAssetTypeService.$inject = ['AppConfig', 'CrudService', 'Logger'];
