//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

export class TaskAlertLogService {
	constructor(AppConfig, CrudService, Logger) {
        this.AppConfig = AppConfig;
        this.CrudService = CrudService;
        this.Logger = Logger
    }

	create(taskAlertLog) {
		this.Logger.debug('TaskAlertLogService.create');
		return this.CrudService.create('TaskAlertLog', taskAlertLog);
    }

	list(filter) {
		this.Logger.debug('TaskAlertLogService.list');
        return this.CrudService.list('TaskAlertLog', filter);
    }

	update(taskAlertLog) {
		this.Logger.debug('TaskAlertLogService.update');
        return this.CrudService.update('TaskAlertLog', taskAlertLog);
    }
}

TaskAlertLogService.$inject = ['AppConfig', 'CrudService', 'Logger'];
