//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

export class TaskTypeService {
	constructor(AppConfig, CrudService, Logger) {
        this.AppConfig = AppConfig;
        this.CrudService = CrudService;
        this.Logger = Logger
    }

	create(taskType) {
		this.Logger.debug('TaskTypeService.create');
		return this.CrudService.create('TaskType', taskType);
    }

	list(filter) {
		this.Logger.debug('TaskTypeService.list');
        return this.CrudService.list('TaskType', filter);
    }

	update(taskType) {
		this.Logger.debug('TaskTypeService.update');
        return this.CrudService.update('TaskType', taskType);
    }
}

TaskTypeService.$inject = ['AppConfig', 'CrudService', 'Logger'];
