//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

export class TaskAlertUserService {
	constructor(AppConfig, CrudService, Logger) {
        this.AppConfig = AppConfig;
        this.CrudService = CrudService;
        this.Logger = Logger
    }

	create(taskAlertUser) {
		this.Logger.debug('TaskAlertUserService.create');
		return this.CrudService.create('TaskAlertUser', taskAlertUser);
    }

	list(filter) {
		this.Logger.debug('TaskAlertUserService.list');
        return this.CrudService.list('TaskAlertUser', filter);
    }

	update(taskAlertUser) {
		this.Logger.debug('TaskAlertUserService.update');
        return this.CrudService.update('TaskAlertUser', taskAlertUser);
    }
}

TaskAlertUserService.$inject = ['AppConfig', 'CrudService', 'Logger'];
