//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

export class UserLogService {
	constructor(AppConfig, CrudService, Logger) {
        this.AppConfig = AppConfig;
        this.CrudService = CrudService;
        this.Logger = Logger
    }

	create(userLog) {
		this.Logger.debug('UserLogService.create');
		return this.CrudService.create('UserLog', userLog);
    }

	list(filter) {
		this.Logger.debug('UserLogService.list');
        return this.CrudService.list('UserLog', filter);
    }

	update(userLog) {
		this.Logger.debug('UserLogService.update');
        return this.CrudService.update('UserLog', userLog);
    }
}

UserLogService.$inject = ['AppConfig', 'CrudService', 'Logger'];
