//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Altask.Data.Model
{
    using Altask.Data;
    using Newtonsoft.Json;
    using System;
    using System.Xml;
    using System;
    using System.Collections.Generic;
    
    public partial class AssetAlert : ISupportsLongId, ISupportsAuthorFields
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssetAlert()
        {
            this.Users = new HashSet<AssetAlertUser>();
        }
    
    	/// <summary>
    	/// Gets or sets the Id of this <see cref='Altask.Data.Model.AssetAlert'/>.
    	/// </summary>
        public long Id { get; set; }
    	/// <summary>
    	/// Gets or sets the Active of this <see cref='Altask.Data.Model.AssetAlert'/>.
    	/// </summary>
        public bool Active { get; set; }
    	/// <summary>
    	/// Gets or sets the AssetId of this <see cref='Altask.Data.Model.AssetAlert'/>.
    	/// </summary>
        public int AssetId { get; set; }
    	/// <summary>
    	/// Gets or sets the AssetLogTypeId of this <see cref='Altask.Data.Model.AssetAlert'/>.
    	/// </summary>
        public int AssetLogTypeId { get; set; }
    	/// <summary>
    	/// Gets or sets the Name of this <see cref='Altask.Data.Model.AssetAlert'/>.
    	/// </summary>
        public string Name { get; set; }
    	/// <summary>
    	/// Gets or sets the Metadata of this <see cref='Altask.Data.Model.AssetAlert'/>.
    	/// </summary>
        public string Metadata { get; set; }
    	/// <summary>
    	/// Gets or sets the CreatedBy of this <see cref='Altask.Data.Model.AssetAlert'/>.
    	/// </summary>
        public string CreatedBy { get; set; }
    	/// <summary>
    	/// Gets or sets the CreatedOn of this <see cref='Altask.Data.Model.AssetAlert'/>.
    	/// </summary>
        public System.DateTime CreatedOn { get; set; }
    	/// <summary>
    	/// Gets or sets the UpdatedBy of this <see cref='Altask.Data.Model.AssetAlert'/>.
    	/// </summary>
        public string UpdatedBy { get; set; }
    	/// <summary>
    	/// Gets or sets the UpdatedOn of this <see cref='Altask.Data.Model.AssetAlert'/>.
    	/// </summary>
        public System.DateTime UpdatedOn { get; set; }
    
        public virtual ICollection<AssetAlertUser> Users { get; set; }
        public virtual AssetLogType LogType { get; set; }
    }
    
    public static partial class Mapper {
    	/// <summary>
    	/// Maps a <see cref='Altask.Data.Model.AssetAlert'/> object to a <see cref='Altask.Data.Dto.AssetAlert'/> object.
    	/// </summary>
    	public static Altask.Data.Dto.AssetAlert ToDto(this Altask.Data.Model.AssetAlert entity) {
    		var dto = new Altask.Data.Dto.AssetAlert();
    		dto.Id = entity.Id;
    		dto.Active = entity.Active;
    		dto.AssetId = entity.AssetId;
    		dto.AssetLogTypeId = entity.AssetLogTypeId;
    		dto.Name = entity.Name;
    		dto.Metadata = JsonConvert.DeserializeObject("{Properties: []}");
    
    		if (!string.IsNullOrEmpty(entity.Metadata)) {
    			try {
    				XmlDocument doc = new XmlDocument();
    				doc.LoadXml(entity.Metadata);
    				string json = Json.SerizlieXmlDocument(doc);
    				dto.Metadata = JsonConvert.DeserializeObject(json);
    			} catch(Exception) {}
    		}
    
    		dto.CreatedBy = entity.CreatedBy;
    		dto.CreatedOn = entity.CreatedOn;
    		dto.UpdatedBy = entity.UpdatedBy;
    		dto.UpdatedOn = entity.UpdatedOn;
    
    		dto.Users = new List<Altask.Data.Dto.AssetAlertUser>();
    		
    		if (entity.Users != null) {
    			foreach(var item in entity.Users) {
    				dto.Users.Add(item.ToDto());
    			}
    		}
    
    		if (entity.LogType != null) {
    			dto.LogType = entity.LogType.ToDto();
    		}
    
    		return dto;
    	}
    
    	/// <summary>
    	/// Maps all the non-primary key and tracking properties of a <see cref='Altask.Data.Dto.AssetAlert'/> object to a <see cref='Altask.Data.Model.AssetAlert'/> object.
    	/// </summary>
    	public static Altask.Data.Model.AssetAlert FromDto(this Altask.Data.Model.AssetAlert model, Altask.Data.Dto.AssetAlert entity) {
    		model.Active = entity.Active;
    		model.AssetId = entity.AssetId;
    		model.AssetLogTypeId = entity.AssetLogTypeId;
    		model.Name = entity.Name;
    		model.Metadata = string.Empty;
    
    		try {
    			model.Metadata = ((XmlDocument)JsonConvert.DeserializeXmlNode(entity.Metadata.ToString(), "Properties")).OuterXml;
    		} catch(Exception) {}
    
    		return model;
    	}
    }
}
