//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Altask.Data.Model
{
    using Altask.Data;
    using Newtonsoft.Json;
    using System;
    using System.Xml;
    using System;
    using System.Collections.Generic;
    
    public partial class OccurrenceLog : ISupportsLongId, ISupportsAuthorFields
    {
    	/// <summary>
    	/// Gets or sets the Id of this <see cref='Altask.Data.Model.OccurrenceLog'/>.
    	/// </summary>
        public long Id { get; set; }
    	/// <summary>
    	/// Gets or sets the OccurrenceId of this <see cref='Altask.Data.Model.OccurrenceLog'/>.
    	/// </summary>
        public long OccurrenceId { get; set; }
    	/// <summary>
    	/// Gets or sets the Type of this <see cref='Altask.Data.Model.OccurrenceLog'/>.
    	/// </summary>
        public string Type { get; set; }
    	/// <summary>
    	/// Gets or sets the Description of this <see cref='Altask.Data.Model.OccurrenceLog'/>.
    	/// </summary>
        public string Description { get; set; }
    	/// <summary>
    	/// Gets or sets the JsonModel of this <see cref='Altask.Data.Model.OccurrenceLog'/>.
    	/// </summary>
        public string JsonModel { get; set; }
    	/// <summary>
    	/// Gets or sets the Metadata of this <see cref='Altask.Data.Model.OccurrenceLog'/>.
    	/// </summary>
        public string Metadata { get; set; }
    	/// <summary>
    	/// Gets or sets the CreatedBy of this <see cref='Altask.Data.Model.OccurrenceLog'/>.
    	/// </summary>
        public string CreatedBy { get; set; }
    	/// <summary>
    	/// Gets or sets the CreatedOn of this <see cref='Altask.Data.Model.OccurrenceLog'/>.
    	/// </summary>
        public System.DateTime CreatedOn { get; set; }
    	/// <summary>
    	/// Gets or sets the UpdatedBy of this <see cref='Altask.Data.Model.OccurrenceLog'/>.
    	/// </summary>
        public string UpdatedBy { get; set; }
    	/// <summary>
    	/// Gets or sets the UpdatedOn of this <see cref='Altask.Data.Model.OccurrenceLog'/>.
    	/// </summary>
        public System.DateTime UpdatedOn { get; set; }
    }
    
    public static partial class Mapper {
    	/// <summary>
    	/// Maps a <see cref='Altask.Data.Model.OccurrenceLog'/> object to a <see cref='Altask.Data.Dto.OccurrenceLog'/> object.
    	/// </summary>
    	/// <param name="includeLogs">Indicates whether to load any logs associated with the object when mapping.</param>
    	public static Altask.Data.Dto.OccurrenceLog ToDto(this Altask.Data.Model.OccurrenceLog entity, bool includeLogs = false) {
    		var dto = new Altask.Data.Dto.OccurrenceLog();
    		dto.Id = entity.Id;
    		dto.OccurrenceId = entity.OccurrenceId;
    		dto.Type = entity.Type;
    		dto.Description = entity.Description;
    		dto.JsonModel = entity.JsonModel;
    		dto.Metadata = JsonConvert.DeserializeObject("{Properties: []}");
    
    		if (!string.IsNullOrEmpty(entity.Metadata)) {
    			try {
    				XmlDocument doc = new XmlDocument();
    				doc.LoadXml(entity.Metadata);
    				string json = Json.SerizlieXmlDocument(doc);
    				dto.Metadata = JsonConvert.DeserializeObject(json);
    			} catch(Exception) {}
    		}
    
    		dto.CreatedBy = entity.CreatedBy;
    		dto.CreatedOn = entity.CreatedOn;
    		dto.UpdatedBy = entity.UpdatedBy;
    		dto.UpdatedOn = entity.UpdatedOn;
    
    		return dto;
    	}
    
    	/// <summary>
    	/// Maps all the non-primary key and tracking properties of a <see cref='Altask.Data.Dto.OccurrenceLog'/> object to a <see cref='Altask.Data.Model.OccurrenceLog'/> object.
    	/// </summary>
    	public static Altask.Data.Model.OccurrenceLog FromDto(this Altask.Data.Model.OccurrenceLog model, Altask.Data.Dto.OccurrenceLog entity) {
    		model.OccurrenceId = entity.OccurrenceId;
    		model.Type = entity.Type;
    		model.Description = entity.Description;
    		model.JsonModel = entity.JsonModel;
    		model.Metadata = string.Empty;
    
    		try {
    			model.Metadata = ((XmlDocument)JsonConvert.DeserializeXmlNode(entity.Metadata.ToString(), "Properties")).OuterXml;
    		} catch(Exception) {}
    
    		return model;
    	}
    }
}
