//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Altask.Data.Model
{
    using Altask.Data;
    using Newtonsoft.Json;
    using System;
    using System.Xml;
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule : ISupportsLongId, ISupportsAuthorFields
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Schedule()
        {
            this.Assets = new HashSet<ScheduleAsset>();
            this.Logs = new HashSet<ScheduleLog>();
            this.Users = new HashSet<ScheduleUser>();
        }
    
    	/// <summary>
    	/// Gets or sets the Id of this <see cref='Altask.Data.Model.Schedule'/>.
    	/// </summary>
        public long Id { get; set; }
    	/// <summary>
    	/// Gets or sets the Active of this <see cref='Altask.Data.Model.Schedule'/>.
    	/// </summary>
        public bool Active { get; set; }
    	/// <summary>
    	/// Gets or sets the TaskId of this <see cref='Altask.Data.Model.Schedule'/>.
    	/// </summary>
        public long TaskId { get; set; }
    	/// <summary>
    	/// Gets or sets the Name of this <see cref='Altask.Data.Model.Schedule'/>.
    	/// </summary>
        public string Name { get; set; }
    	/// <summary>
    	/// Gets or sets the Description of this <see cref='Altask.Data.Model.Schedule'/>.
    	/// </summary>
        public string Description { get; set; }
    	/// <summary>
    	/// Gets or sets the Frequency of this <see cref='Altask.Data.Model.Schedule'/>.
    	/// </summary>
        public string Frequency { get; set; }
    	/// <summary>
    	/// Gets or sets the EndsAfter of this <see cref='Altask.Data.Model.Schedule'/>.
    	/// </summary>
        public Nullable<int> EndsAfter { get; set; }
    	/// <summary>
    	/// Gets or sets the EndsOn of this <see cref='Altask.Data.Model.Schedule'/>.
    	/// </summary>
        public Nullable<System.DateTime> EndsOn { get; set; }
    	/// <summary>
    	/// Gets or sets the EveryN of this <see cref='Altask.Data.Model.Schedule'/>.
    	/// </summary>
        public Nullable<int> EveryN { get; set; }
    	/// <summary>
    	/// Gets or sets the OnWeek of this <see cref='Altask.Data.Model.Schedule'/>.
    	/// </summary>
        public Nullable<int> OnWeek { get; set; }
    	/// <summary>
    	/// Gets or sets the AnyTime of this <see cref='Altask.Data.Model.Schedule'/>.
    	/// </summary>
        public Nullable<bool> AnyTime { get; set; }
    	/// <summary>
    	/// Gets or sets the AsEarlyAsN of this <see cref='Altask.Data.Model.Schedule'/>.
    	/// </summary>
        public Nullable<int> AsEarlyAsN { get; set; }
    	/// <summary>
    	/// Gets or sets the AsEarlyAsFrequency of this <see cref='Altask.Data.Model.Schedule'/>.
    	/// </summary>
        public string AsEarlyAsFrequency { get; set; }
    	/// <summary>
    	/// Gets or sets the OnMonday of this <see cref='Altask.Data.Model.Schedule'/>.
    	/// </summary>
        public bool OnMonday { get; set; }
    	/// <summary>
    	/// Gets or sets the OnTuesday of this <see cref='Altask.Data.Model.Schedule'/>.
    	/// </summary>
        public bool OnTuesday { get; set; }
    	/// <summary>
    	/// Gets or sets the OnWednesday of this <see cref='Altask.Data.Model.Schedule'/>.
    	/// </summary>
        public bool OnWednesday { get; set; }
    	/// <summary>
    	/// Gets or sets the OnThursday of this <see cref='Altask.Data.Model.Schedule'/>.
    	/// </summary>
        public bool OnThursday { get; set; }
    	/// <summary>
    	/// Gets or sets the OnFriday of this <see cref='Altask.Data.Model.Schedule'/>.
    	/// </summary>
        public bool OnFriday { get; set; }
    	/// <summary>
    	/// Gets or sets the OnSaturday of this <see cref='Altask.Data.Model.Schedule'/>.
    	/// </summary>
        public bool OnSaturday { get; set; }
    	/// <summary>
    	/// Gets or sets the OnSunday of this <see cref='Altask.Data.Model.Schedule'/>.
    	/// </summary>
        public bool OnSunday { get; set; }
    	/// <summary>
    	/// Gets or sets the StartsOn of this <see cref='Altask.Data.Model.Schedule'/>.
    	/// </summary>
        public System.DateTime StartsOn { get; set; }
    	/// <summary>
    	/// Gets or sets the CreatedBy of this <see cref='Altask.Data.Model.Schedule'/>.
    	/// </summary>
        public string CreatedBy { get; set; }
    	/// <summary>
    	/// Gets or sets the CreatedOn of this <see cref='Altask.Data.Model.Schedule'/>.
    	/// </summary>
        public System.DateTime CreatedOn { get; set; }
    	/// <summary>
    	/// Gets or sets the UpdatedBy of this <see cref='Altask.Data.Model.Schedule'/>.
    	/// </summary>
        public string UpdatedBy { get; set; }
    	/// <summary>
    	/// Gets or sets the UpdatedOn of this <see cref='Altask.Data.Model.Schedule'/>.
    	/// </summary>
        public System.DateTime UpdatedOn { get; set; }
    
        public virtual ICollection<ScheduleAsset> Assets { get; set; }
        public virtual ICollection<ScheduleLog> Logs { get; set; }
        public virtual ICollection<ScheduleUser> Users { get; set; }
    }
    
    public static partial class Mapper {
    	/// <summary>
    	/// Maps a <see cref='Altask.Data.Model.Schedule'/> object to a <see cref='Altask.Data.Dto.Schedule'/> object.
    	/// </summary>
    	/// <param name="includeLogs">Indicates whether to load any logs associated with the object when mapping.</param>
    	public static Altask.Data.Dto.Schedule ToDto(this Altask.Data.Model.Schedule entity, bool includeLogs = false) {
    		var dto = new Altask.Data.Dto.Schedule();
    		dto.Id = entity.Id;
    		dto.Active = entity.Active;
    		dto.TaskId = entity.TaskId;
    		dto.Name = entity.Name;
    		dto.Description = entity.Description;
    		dto.Frequency = entity.Frequency;
    		dto.EndsAfter = entity.EndsAfter;
    		dto.EndsOn = entity.EndsOn;
    		dto.EveryN = entity.EveryN;
    		dto.OnWeek = entity.OnWeek;
    		dto.AnyTime = entity.AnyTime;
    		dto.AsEarlyAsN = entity.AsEarlyAsN;
    		dto.AsEarlyAsFrequency = entity.AsEarlyAsFrequency;
    		dto.OnMonday = entity.OnMonday;
    		dto.OnTuesday = entity.OnTuesday;
    		dto.OnWednesday = entity.OnWednesday;
    		dto.OnThursday = entity.OnThursday;
    		dto.OnFriday = entity.OnFriday;
    		dto.OnSaturday = entity.OnSaturday;
    		dto.OnSunday = entity.OnSunday;
    		dto.StartsOn = entity.StartsOn;
    		dto.CreatedBy = entity.CreatedBy;
    		dto.CreatedOn = entity.CreatedOn;
    		dto.UpdatedBy = entity.UpdatedBy;
    		dto.UpdatedOn = entity.UpdatedOn;
    
    		dto.Assets = new List<Altask.Data.Dto.ScheduleAsset>();
    		
    		if (entity.Assets != null) {
    			foreach(var item in entity.Assets) {
    				dto.Assets.Add(item.ToDto());
    			}
    		}
    
    		dto.Logs = new List<Altask.Data.Dto.ScheduleLog>();
    
    		if (includeLogs) {
    			if (entity.Logs != null) {
    				foreach(var item in entity.Logs) {
    					dto.Logs.Add(item.ToDto());
    				}
    			}
    		}
    			
    		return dto;
    	}
    
    	/// <summary>
    	/// Maps all the non-primary key and tracking properties of a <see cref='Altask.Data.Dto.Schedule'/> object to a <see cref='Altask.Data.Model.Schedule'/> object.
    	/// </summary>
    	public static Altask.Data.Model.Schedule FromDto(this Altask.Data.Model.Schedule model, Altask.Data.Dto.Schedule entity) {
    		model.Active = entity.Active;
    		model.TaskId = entity.TaskId;
    		model.Name = entity.Name;
    		model.Description = entity.Description;
    		model.Frequency = entity.Frequency;
    		model.EndsAfter = entity.EndsAfter;
    		model.EndsOn = entity.EndsOn;
    		model.EveryN = entity.EveryN;
    		model.OnWeek = entity.OnWeek;
    		model.AnyTime = entity.AnyTime;
    		model.AsEarlyAsN = entity.AsEarlyAsN;
    		model.AsEarlyAsFrequency = entity.AsEarlyAsFrequency;
    		model.OnMonday = entity.OnMonday;
    		model.OnTuesday = entity.OnTuesday;
    		model.OnWednesday = entity.OnWednesday;
    		model.OnThursday = entity.OnThursday;
    		model.OnFriday = entity.OnFriday;
    		model.OnSaturday = entity.OnSaturday;
    		model.OnSunday = entity.OnSunday;
    		model.StartsOn = entity.StartsOn;
    		return model;
    	}
    }
}
