//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Altask.Data.Model
{
    using Altask.Data;
    using Newtonsoft.Json;
    using System;
    using System.Xml;
    using System;
    using System.Collections.Generic;
    
    public partial class Setting : ISupportsIntId, ISupportsAuthorFields
    {
    	/// <summary>
    	/// Gets or sets the Id of this <see cref='Altask.Data.Model.Setting'/>.
    	/// </summary>
        public int Id { get; set; }
    	/// <summary>
    	/// Gets or sets the Name of this <see cref='Altask.Data.Model.Setting'/>.
    	/// </summary>
        public string Name { get; set; }
    	/// <summary>
    	/// Gets or sets the Area of this <see cref='Altask.Data.Model.Setting'/>.
    	/// </summary>
        public string Area { get; set; }
    	/// <summary>
    	/// Gets or sets the Classification of this <see cref='Altask.Data.Model.Setting'/>.
    	/// </summary>
        public string Classification { get; set; }
    	/// <summary>
    	/// Gets or sets the Value of this <see cref='Altask.Data.Model.Setting'/>.
    	/// </summary>
        public string Value { get; set; }
    	/// <summary>
    	/// Gets or sets the CreatedBy of this <see cref='Altask.Data.Model.Setting'/>.
    	/// </summary>
        public string CreatedBy { get; set; }
    	/// <summary>
    	/// Gets or sets the CreatedOn of this <see cref='Altask.Data.Model.Setting'/>.
    	/// </summary>
        public System.DateTime CreatedOn { get; set; }
    	/// <summary>
    	/// Gets or sets the UpdatedBy of this <see cref='Altask.Data.Model.Setting'/>.
    	/// </summary>
        public string UpdatedBy { get; set; }
    	/// <summary>
    	/// Gets or sets the UpdatedOn of this <see cref='Altask.Data.Model.Setting'/>.
    	/// </summary>
        public System.DateTime UpdatedOn { get; set; }
    }
    
    public static partial class Mapper {
    	/// <summary>
    	/// Maps a <see cref='Altask.Data.Model.Setting'/> object to a <see cref='Altask.Data.Dto.Setting'/> object.
    	/// </summary>
    	/// <param name="includeLogs">Indicates whether to load any logs associated with the object when mapping.</param>
    	public static Altask.Data.Dto.Setting ToDto(this Altask.Data.Model.Setting entity, bool includeLogs = false) {
    		var dto = new Altask.Data.Dto.Setting();
    		dto.Id = entity.Id;
    		dto.Name = entity.Name;
    		dto.Area = entity.Area;
    		dto.Classification = entity.Classification;
    		dto.Value = entity.Value;
    		dto.CreatedBy = entity.CreatedBy;
    		dto.CreatedOn = entity.CreatedOn;
    		dto.UpdatedBy = entity.UpdatedBy;
    		dto.UpdatedOn = entity.UpdatedOn;
    
    		return dto;
    	}
    
    	/// <summary>
    	/// Maps all the non-primary key and tracking properties of a <see cref='Altask.Data.Dto.Setting'/> object to a <see cref='Altask.Data.Model.Setting'/> object.
    	/// </summary>
    	public static Altask.Data.Model.Setting FromDto(this Altask.Data.Model.Setting model, Altask.Data.Dto.Setting entity) {
    		model.Name = entity.Name;
    		model.Area = entity.Area;
    		model.Classification = entity.Classification;
    		model.Value = entity.Value;
    		return model;
    	}
    }
}
