//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Altask.www.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Linq;
    using System.Threading.Tasks;
    using System.Web.Mvc;
    using System.Xml;
    using Altask.www.Models;
    using Data.Model;
    
    [Authorize]
    public partial class AssetLogTypeAssetController : BaseController<Altask.Data.Model.AssetLogTypeAsset, Altask.Data.Dto.AssetLogTypeAsset>
    {
    	/// <summary>
    	/// Constructor
    	/// </summary>
    	public AssetLogTypeAssetController() : base() {
    	
    	}
    
    	/// <summary>
    	/// Constructor
    	/// </summary>
    	/// <param name="userManager">The application user manager used in this application. UserManager is defined in ASP.NET Identity and is used by the application.</param>
    	/// <param name="signInManager">The application sign-in manager which is used in this application.</param>
    	public AssetLogTypeAssetController(ApplicationUserManager userManager, ApplicationSignInManager signInManager) : base(userManager, signInManager) {
    
    	}
    
    	[HttpPost]
    	[JsonNetFilter]
    	/// <summary>
    	/// Create a <see cref="Altask.Data.Model.AssetLogTypeAsset"/>.
    	/// </summary>
    	/// <param name="assetLogTypeAsset"></param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> Create(Altask.Data.Dto.AssetLogTypeAsset assetLogTypeAsset) {
    		ThrowIfDisposed();
    
    		if (!ModelState.IsValid) {
    			return BadRequest(ModelState);
    		}
    
    		var newAssetLogTypeAsset = new Altask.Data.Model.AssetLogTypeAsset().FromDto(assetLogTypeAsset);
    		Context.AssetLogTypeAssets.Add(newAssetLogTypeAsset);
    		BeforeCreate(newAssetLogTypeAsset, assetLogTypeAsset);
    		var result = await Context.SaveChangesAsync();
        
        	if (result.Succeeded) {
    			await AfterCreateAsync(newAssetLogTypeAsset);
    			return Ok(new { assetLogTypeAsset = newAssetLogTypeAsset.ToDto() });
        	} else {
        		return BadRequest(result);
        	}
    	}
    
    	[HttpGet]
    	[JsonNetFilter]
    	/// <summary>
    	/// Returns a <see cref="Altask.Data.Model.AssetLogTypeAsset"/> having the specified ID.
    	/// </summary>
    	/// <param name="id">The ID of the <see cref="Altask.Data.Model.AssetLogTypeAsset"/>.</param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> FindById(long id) {
    		ThrowIfDisposed();
    		var assetLogTypeAsset = await Context.AssetLogTypeAssets.FindAsync(id);
    		return Ok(new { assetLogTypeAsset = assetLogTypeAsset.ToDto() }, JsonRequestBehavior.AllowGet);
    	}
    
    	[HttpGet]
    	[JsonNetFilter]
    	/// <summary>
    	/// Returns a collection of <see cref="Altask.Data.Model.AssetLogTypeAsset"/> objects.
    	/// </summary>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> List() {
    		ThrowIfDisposed();
    		var dtoAssetLogTypeAssets = new List<Altask.Data.Dto.AssetLogTypeAsset>();
    		var assetLogTypeAsset = await Context.AssetLogTypeAssets.ToListAsync();
    
    		foreach(var item in assetLogTypeAsset) {
    			dtoAssetLogTypeAssets.Add(item.ToDto());
    		}
    
    		return Ok(new { assetLogTypeAssets = dtoAssetLogTypeAssets }, JsonRequestBehavior.AllowGet);
    	}
    
    	[HttpPost]
    	[JsonNetFilter]
    	/// <summary>
    	/// Updates the specified <see cref="Altask.Data.Model.AssetLogTypeAsset"/>.
    	/// </summary>
    	/// <param name="assetLogTypeAsset"></param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> Update(Altask.Data.Dto.AssetLogTypeAsset assetLogTypeAsset) {
    		ThrowIfDisposed();
    
    		if (!ModelState.IsValid) {
    			return BadRequest(ModelState);
    		}
    
    		var assetLogTypeAssetEntity = await Context.AssetLogTypeAssets.FindAsync(assetLogTypeAsset.Id);
    
    		if (assetLogTypeAssetEntity == null) {
    			return BadRequest(ErrorDescriber.DoesNotExist("AssetLogTypeAsset"));
    		}
    
    		assetLogTypeAssetEntity.FromDto(assetLogTypeAsset);
    		Context.Entry(assetLogTypeAssetEntity).State = EntityState.Modified;
    		BeforeUpdate(assetLogTypeAssetEntity, assetLogTypeAsset);
    		var result = await Context.SaveChangesAsync();
        
        	if (result.Succeeded) {
    			await AfterUpdateAsync(assetLogTypeAssetEntity);
    			return Ok(new { assetLogTypeAsset = assetLogTypeAssetEntity.ToDto() });
        	} else {
        		return BadRequest(result);
        	}
    	}
    }
}
