//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Altask.www.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Linq;
    using System.Threading.Tasks;
    using System.Web.Mvc;
    using System.Xml;
    using Altask.www.Models;
    using Data.Model;
    
    [Authorize]
    public partial class AssetTypeController : BaseController<Altask.Data.Model.AssetType, Altask.Data.Dto.AssetType>
    {
    	/// <summary>
    	/// Constructor
    	/// </summary>
    	public AssetTypeController() : base() {
    	
    	}
    
    	/// <summary>
    	/// Constructor
    	/// </summary>
    	/// <param name="userManager">The application user manager used in this application. UserManager is defined in ASP.NET Identity and is used by the application.</param>
    	/// <param name="signInManager">The application sign-in manager which is used in this application.</param>
    	public AssetTypeController(ApplicationUserManager userManager, ApplicationSignInManager signInManager) : base(userManager, signInManager) {
    
    	}
    
    	[HttpPost]
    	[JsonNetFilter]
    	/// <summary>
    	/// Create a <see cref="Altask.Data.Model.AssetType"/>.
    	/// </summary>
    	/// <param name="assetType"></param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> Create(Altask.Data.Dto.AssetType assetType) {
    		ThrowIfDisposed();
    
    		if (!ModelState.IsValid) {
    			return BadRequest(ModelState);
    		}
    
    		var newAssetType = new Altask.Data.Model.AssetType().FromDto(assetType);
    		Context.AssetTypes.Add(newAssetType);
    		BeforeCreate(newAssetType, assetType);
    		var result = await Context.SaveChangesAsync();
        
        	if (result.Succeeded) {
    			await AfterCreateAsync(newAssetType);
    			return Ok(new { assetType = newAssetType.ToDto() });
        	} else {
        		return BadRequest(result);
        	}
    	}
    
    	[HttpGet]
    	[JsonNetFilter]
    	/// <summary>
    	/// Returns a <see cref="Altask.Data.Model.AssetType"/> having the specified ID.
    	/// </summary>
    	/// <param name="id">The ID of the <see cref="Altask.Data.Model.AssetType"/>.</param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> FindById(int id) {
    		ThrowIfDisposed();
    		var assetType = await Context.AssetTypes.FindAsync(id);
    		return Ok(new { assetType = assetType.ToDto() }, JsonRequestBehavior.AllowGet);
    	}
    
    	[HttpGet]
    	[JsonNetFilter]
    	/// <summary>
    	/// Returns a collection of <see cref="Altask.Data.Model.AssetType"/> objects matching the specified filter.
    	/// </summary>
    	/// <param name="filter">A <see cref="Altask.www.Models.AssetTypeListOptions"/> object on which to filter.</param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> List(AssetTypeListOptions filter) {
    		ThrowIfDisposed();
    
    		if (filter == null) {
    			filter = new AssetTypeListOptions();
    		}
    
    		var dtoAssetTypes = new List<Altask.Data.Dto.AssetType>();
    		var assetType = await Context.AssetTypes.AsNoTracking().Where(filter.GetPredicate())
    			.ToListAsync();
    
    		foreach(var item in assetType) {
    			dtoAssetTypes.Add(item.ToDto());
    		}
    
    		return Ok(new { assetTypes = dtoAssetTypes }, JsonRequestBehavior.AllowGet);
    	}
    
    	[HttpPost]
    	[JsonNetFilter]
    	/// <summary>
    	/// Updates the specified <see cref="Altask.Data.Model.AssetType"/>.
    	/// </summary>
    	/// <param name="assetType"></param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> Update(Altask.Data.Dto.AssetType assetType) {
    		ThrowIfDisposed();
    
    		if (!ModelState.IsValid) {
    			return BadRequest(ModelState);
    		}
    
    		var assetTypeEntity = await Context.AssetTypes.FindAsync(assetType.Id);
    
    		if (assetTypeEntity == null) {
    			return BadRequest(ErrorDescriber.DoesNotExist("AssetType"));
    		}
    
    		assetTypeEntity.FromDto(assetType);
    		Context.Entry(assetTypeEntity).State = EntityState.Modified;
    		BeforeUpdate(assetTypeEntity, assetType);
    		var result = await Context.SaveChangesAsync();
        
        	if (result.Succeeded) {
    			await AfterUpdateAsync(assetTypeEntity);
    			return Ok(new { assetType = assetTypeEntity.ToDto() });
        	} else {
        		return BadRequest(result);
        	}
    	}
    }
}
