//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Altask.www.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Linq;
    using System.Threading.Tasks;
    using System.Web.Mvc;
    using System.Xml;
    using Altask.www.Models;
    using Data.Model;
    
    [Authorize]
    public partial class AssetLogResolutionController : BaseController<Altask.Data.Model.AssetLogResolution, Altask.Data.Dto.AssetLogResolution>
    {
    	/// <summary>
    	/// Constructor
    	/// </summary>
    	public AssetLogResolutionController() : base() {
    	
    	}
    
    	/// <summary>
    	/// Constructor
    	/// </summary>
    	/// <param name="userManager">The application user manager used in this application. UserManager is defined in ASP.NET Identity and is used by the application.</param>
    	/// <param name="signInManager">The application sign-in manager which is used in this application.</param>
    	public AssetLogResolutionController(ApplicationUserManager userManager, ApplicationSignInManager signInManager) : base(userManager, signInManager) {
    
    	}
    
    	[HttpPost]
    	[JsonNetFilter]
    	/// <summary>
    	/// Create a <see cref="Altask.Data.Model.AssetLogResolution"/>.
    	/// </summary>
    	/// <param name="assetLogResolution"></param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> Create(Altask.Data.Dto.AssetLogResolution assetLogResolution) {
    		ThrowIfDisposed();
    
    		if (!ModelState.IsValid) {
    			return BadRequest(ModelState);
    		}
    
    		var newAssetLogResolution = new Altask.Data.Model.AssetLogResolution().FromDto(assetLogResolution);
    		Context.AssetLogResolutions.Add(newAssetLogResolution);
    		BeforeCreate(newAssetLogResolution, assetLogResolution);
    		var result = await Context.SaveChangesAsync();
    		Context.Entry(newAssetLogResolution).Reference(e => e.Occurrence).Load();
    		Context.Entry(newAssetLogResolution).Reference(e => e.Task).Load();
        
        	if (result.Succeeded) {
    			await AfterCreateAsync(newAssetLogResolution);
    			return Ok(new { assetLogResolution = newAssetLogResolution.ToDto() });
        	} else {
        		return BadRequest(result);
        	}
    	}
    
    	[HttpGet]
    	[JsonNetFilter]
    	/// <summary>
    	/// Returns a <see cref="Altask.Data.Model.AssetLogResolution"/> having the specified ID.
    	/// </summary>
    	/// <param name="id">The ID of the <see cref="Altask.Data.Model.AssetLogResolution"/>.</param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> FindById(long id) {
    		ThrowIfDisposed();
    		var assetLogResolution = await Context.AssetLogResolutions.FindAsync(id);
    		return Ok(new { assetLogResolution = assetLogResolution.ToDto() }, JsonRequestBehavior.AllowGet);
    	}
    
    	[HttpGet]
    	[JsonNetFilter]
    	/// <summary>
    	/// Returns a collection of <see cref="Altask.Data.Model.AssetLogResolution"/> objects matching the specified filter.
    	/// </summary>
    	/// <param name="filter">A <see cref="Altask.www.Models.AssetLogResolutionListOptions"/> object on which to filter.</param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> List(AssetLogResolutionListOptions filter) {
    		ThrowIfDisposed();
    
    		if (filter == null) {
    			filter = new AssetLogResolutionListOptions();
    		}
    
    		var dtoAssetLogResolutions = new List<Altask.Data.Dto.AssetLogResolution>();
    		var assetLogResolution = await Context.AssetLogResolutions.AsNoTracking().Where(filter.GetPredicate())
    			.Include(e => e.Occurrence)
    			.Include(e => e.Task)
    			.ToListAsync();
    
    		foreach(var item in assetLogResolution) {
    			dtoAssetLogResolutions.Add(item.ToDto());
    		}
    
    		return Ok(new { assetLogResolutions = dtoAssetLogResolutions }, JsonRequestBehavior.AllowGet);
    	}
    
    	[HttpPost]
    	[JsonNetFilter]
    	/// <summary>
    	/// Updates the specified <see cref="Altask.Data.Model.AssetLogResolution"/>.
    	/// </summary>
    	/// <param name="assetLogResolution"></param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> Update(Altask.Data.Dto.AssetLogResolution assetLogResolution) {
    		ThrowIfDisposed();
    
    		if (!ModelState.IsValid) {
    			return BadRequest(ModelState);
    		}
    
    		var assetLogResolutionEntity = await Context.AssetLogResolutions.FindAsync(assetLogResolution.Id);
    
    		if (assetLogResolutionEntity == null) {
    			return BadRequest(ErrorDescriber.DoesNotExist("AssetLogResolution"));
    		}
    
    		assetLogResolutionEntity.FromDto(assetLogResolution);
    		Context.Entry(assetLogResolutionEntity).State = EntityState.Modified;
    		BeforeUpdate(assetLogResolutionEntity, assetLogResolution);
    		var result = await Context.SaveChangesAsync();
    		Context.Entry(assetLogResolutionEntity).Reference(e => e.Occurrence).Load();
    		Context.Entry(assetLogResolutionEntity).Reference(e => e.Task).Load();
        
        	if (result.Succeeded) {
    			await AfterUpdateAsync(assetLogResolutionEntity);
    			return Ok(new { assetLogResolution = assetLogResolutionEntity.ToDto() });
        	} else {
        		return BadRequest(result);
        	}
    	}
    }
}
