//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Altask.www.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Linq;
    using System.Threading.Tasks;
    using System.Web.Mvc;
    using System.Xml;
    using Altask.www.Models;
    using Data.Model;
    
    [Authorize]
    public partial class AssetAlertLogController : BaseController<Altask.Data.Model.AssetAlertLog, Altask.Data.Dto.AssetAlertLog>
    {
    	/// <summary>
    	/// Constructor
    	/// </summary>
    	public AssetAlertLogController() : base() {
    	
    	}
    
    	/// <summary>
    	/// Constructor
    	/// </summary>
    	/// <param name="userManager">The application user manager used in this application. UserManager is defined in ASP.NET Identity and is used by the application.</param>
    	/// <param name="signInManager">The application sign-in manager which is used in this application.</param>
    	public AssetAlertLogController(ApplicationUserManager userManager, ApplicationSignInManager signInManager) : base(userManager, signInManager) {
    
    	}
    
    	[HttpPost]
    	[JsonNetFilter]
    	/// <summary>
    	/// Create a <see cref="Altask.Data.Model.AssetAlertLog"/>.
    	/// </summary>
    	/// <param name="assetAlertLog"></param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> Create(Altask.Data.Dto.AssetAlertLog assetAlertLog) {
    		ThrowIfDisposed();
    
    		if (!ModelState.IsValid) {
    			return BadRequest(ModelState);
    		}
    
    		var newAssetAlertLog = new Altask.Data.Model.AssetAlertLog().FromDto(assetAlertLog);
    		Context.AssetAlertLogs.Add(newAssetAlertLog);
    		BeforeCreate(newAssetAlertLog, assetAlertLog);
    		var result = await Context.SaveChangesAsync();
    		Context.Entry(newAssetAlertLog).Reference(e => e.User).Load();
    		Context.Entry(newAssetAlertLog).Reference(e => e.AssetLog).Load();
        
        	if (result.Succeeded) {
    			await AfterCreateAsync(newAssetAlertLog);
    			return Ok(new { assetAlertLog = newAssetAlertLog.ToDto() });
        	} else {
        		return BadRequest(result);
        	}
    	}
    
    	[HttpGet]
    	[JsonNetFilter]
    	/// <summary>
    	/// Returns a <see cref="Altask.Data.Model.AssetAlertLog"/> having the specified ID.
    	/// </summary>
    	/// <param name="id">The ID of the <see cref="Altask.Data.Model.AssetAlertLog"/>.</param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> FindById(long id) {
    		ThrowIfDisposed();
    		var assetAlertLog = await Context.AssetAlertLogs.FindAsync(id);
    		return Ok(new { assetAlertLog = assetAlertLog.ToDto() }, JsonRequestBehavior.AllowGet);
    	}
    
    	[HttpGet]
    	[JsonNetFilter]
    	/// <summary>
    	/// Returns a collection of <see cref="Altask.Data.Model.AssetAlertLog"/> objects matching the specified filter.
    	/// </summary>
    	/// <param name="filter">A <see cref="Altask.www.Models.AssetAlertLogListOptions"/> object on which to filter.</param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> List(AssetAlertLogListOptions filter) {
    		ThrowIfDisposed();
    
    		if (filter == null) {
    			filter = new AssetAlertLogListOptions();
    		}
    
    		var dtoAssetAlertLogs = new List<Altask.Data.Dto.AssetAlertLog>();
    		var assetAlertLog = await Context.AssetAlertLogs.AsNoTracking().Where(filter.GetPredicate())
    			.Include(e => e.User)
    			.Include(e => e.AssetLog)
    			.ToListAsync();
    
    		foreach(var item in assetAlertLog) {
    			dtoAssetAlertLogs.Add(item.ToDto());
    		}
    
    		return Ok(new { assetAlertLogs = dtoAssetAlertLogs }, JsonRequestBehavior.AllowGet);
    	}
    
    	[HttpPost]
    	[JsonNetFilter]
    	/// <summary>
    	/// Updates the specified <see cref="Altask.Data.Model.AssetAlertLog"/>.
    	/// </summary>
    	/// <param name="assetAlertLog"></param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> Update(Altask.Data.Dto.AssetAlertLog assetAlertLog) {
    		ThrowIfDisposed();
    
    		if (!ModelState.IsValid) {
    			return BadRequest(ModelState);
    		}
    
    		var assetAlertLogEntity = await Context.AssetAlertLogs.FindAsync(assetAlertLog.Id);
    
    		if (assetAlertLogEntity == null) {
    			return BadRequest(ErrorDescriber.DoesNotExist("AssetAlertLog"));
    		}
    
    		assetAlertLogEntity.FromDto(assetAlertLog);
    		Context.Entry(assetAlertLogEntity).State = EntityState.Modified;
    		BeforeUpdate(assetAlertLogEntity, assetAlertLog);
    		var result = await Context.SaveChangesAsync();
    		Context.Entry(assetAlertLogEntity).Reference(e => e.User).Load();
    		Context.Entry(assetAlertLogEntity).Reference(e => e.AssetLog).Load();
        
        	if (result.Succeeded) {
    			await AfterUpdateAsync(assetAlertLogEntity);
    			return Ok(new { assetAlertLog = assetAlertLogEntity.ToDto() });
        	} else {
        		return BadRequest(result);
        	}
    	}
    }
}
