//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Altask.www.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Linq;
    using System.Threading.Tasks;
    using System.Web.Mvc;
    using System.Xml;
    using Altask.www.Models;
    using Data.Model;
    
    [Authorize]
    public partial class ScheduleAssetTypeController : BaseController<Altask.Data.Model.ScheduleAssetType, Altask.Data.Dto.ScheduleAssetType>
    {
    	/// <summary>
    	/// Constructor
    	/// </summary>
    	public ScheduleAssetTypeController() : base() {
    	
    	}
    
    	/// <summary>
    	/// Constructor
    	/// </summary>
    	/// <param name="userManager">The application user manager used in this application. UserManager is defined in ASP.NET Identity and is used by the application.</param>
    	/// <param name="signInManager">The application sign-in manager which is used in this application.</param>
    	public ScheduleAssetTypeController(ApplicationUserManager userManager, ApplicationSignInManager signInManager) : base(userManager, signInManager) {
    
    	}
    
    	[HttpPost]
    	[JsonNetFilter]
    	/// <summary>
    	/// Create a <see cref="Altask.Data.Model.ScheduleAssetType"/>.
    	/// </summary>
    	/// <param name="scheduleAssetType"></param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> Create(Altask.Data.Dto.ScheduleAssetType scheduleAssetType) {
    		ThrowIfDisposed();
    
    		if (!ModelState.IsValid) {
    			return BadRequest(ModelState);
    		}
    
    		var newScheduleAssetType = new Altask.Data.Model.ScheduleAssetType().FromDto(scheduleAssetType);
    		Context.ScheduleAssetTypes.Add(newScheduleAssetType);
    		BeforeCreate(newScheduleAssetType, scheduleAssetType);
    		var result = await Context.SaveChangesAsync();
        
        	if (result.Succeeded) {
    			await AfterCreateAsync(newScheduleAssetType);
    			return Ok(new { scheduleAssetType = newScheduleAssetType.ToDto() });
        	} else {
        		return BadRequest(result);
        	}
    	}
    
    	[HttpGet]
    	[JsonNetFilter]
    	/// <summary>
    	/// Returns a <see cref="Altask.Data.Model.ScheduleAssetType"/> having the specified ID.
    	/// </summary>
    	/// <param name="id">The ID of the <see cref="Altask.Data.Model.ScheduleAssetType"/>.</param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> FindById(int id) {
    		ThrowIfDisposed();
    		var scheduleAssetType = await Context.ScheduleAssetTypes.FindAsync(id);
    		return Ok(new { scheduleAssetType = scheduleAssetType.ToDto() }, JsonRequestBehavior.AllowGet);
    	}
    
    	[HttpGet]
    	[JsonNetFilter]
    	/// <summary>
    	/// Returns a collection of <see cref="Altask.Data.Model.ScheduleAssetType"/> objects matching the specified filter.
    	/// </summary>
    	/// <param name="filter">A <see cref="Altask.www.Models.ScheduleAssetTypeListOptions"/> object on which to filter.</param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> List(ScheduleAssetTypeListOptions filter) {
    		ThrowIfDisposed();
    
    		if (filter == null) {
    			filter = new ScheduleAssetTypeListOptions();
    		}
    
    		var dtoScheduleAssetTypes = new List<Altask.Data.Dto.ScheduleAssetType>();
    		var scheduleAssetType = await Context.ScheduleAssetTypes.AsNoTracking().Where(filter.GetPredicate())
    			.ToListAsync();
    
    		foreach(var item in scheduleAssetType) {
    			dtoScheduleAssetTypes.Add(item.ToDto());
    		}
    
    		return Ok(new { scheduleAssetTypes = dtoScheduleAssetTypes }, JsonRequestBehavior.AllowGet);
    	}
    
    	[HttpPost]
    	[JsonNetFilter]
    	/// <summary>
    	/// Updates the specified <see cref="Altask.Data.Model.ScheduleAssetType"/>.
    	/// </summary>
    	/// <param name="scheduleAssetType"></param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> Update(Altask.Data.Dto.ScheduleAssetType scheduleAssetType) {
    		ThrowIfDisposed();
    
    		if (!ModelState.IsValid) {
    			return BadRequest(ModelState);
    		}
    
    		var scheduleAssetTypeEntity = await Context.ScheduleAssetTypes.FindAsync(scheduleAssetType.Id);
    
    		if (scheduleAssetTypeEntity == null) {
    			return BadRequest(ErrorDescriber.DoesNotExist("ScheduleAssetType"));
    		}
    
    		scheduleAssetTypeEntity.FromDto(scheduleAssetType);
    		Context.Entry(scheduleAssetTypeEntity).State = EntityState.Modified;
    		BeforeUpdate(scheduleAssetTypeEntity, scheduleAssetType);
    		var result = await Context.SaveChangesAsync();
        
        	if (result.Succeeded) {
    			await AfterUpdateAsync(scheduleAssetTypeEntity);
    			return Ok(new { scheduleAssetType = scheduleAssetTypeEntity.ToDto() });
        	} else {
        		return BadRequest(result);
        	}
    	}
    }
}
