//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Altask.Data.Model
{
    using Altask.Data;
    using Newtonsoft.Json;
    using System;
    using System.Xml;
    using System;
    using System.Collections.Generic;
    
    public partial class AssetAlertUser : ISupportsLongId, ISupportsAuthorFields
    {
    	/// <summary>
    	/// Gets or sets the Id of this <see cref='Altask.Data.Model.AssetAlertUser'/>.
    	/// </summary>
        public long Id { get; set; }
    	/// <summary>
    	/// Gets or sets the AssetAlertId of this <see cref='Altask.Data.Model.AssetAlertUser'/>.
    	/// </summary>
        public long AssetAlertId { get; set; }
    	/// <summary>
    	/// Gets or sets the UserId of this <see cref='Altask.Data.Model.AssetAlertUser'/>.
    	/// </summary>
        public int UserId { get; set; }
    	/// <summary>
    	/// Gets or sets the CreatedBy of this <see cref='Altask.Data.Model.AssetAlertUser'/>.
    	/// </summary>
        public string CreatedBy { get; set; }
    	/// <summary>
    	/// Gets or sets the CreatedOn of this <see cref='Altask.Data.Model.AssetAlertUser'/>.
    	/// </summary>
        public System.DateTime CreatedOn { get; set; }
    	/// <summary>
    	/// Gets or sets the UpdatedBy of this <see cref='Altask.Data.Model.AssetAlertUser'/>.
    	/// </summary>
        public string UpdatedBy { get; set; }
    	/// <summary>
    	/// Gets or sets the UpdatedOn of this <see cref='Altask.Data.Model.AssetAlertUser'/>.
    	/// </summary>
        public System.DateTime UpdatedOn { get; set; }
    
        public virtual User User { get; set; }
    }
    
    public static partial class Mapper {
    	/// <summary>
    	/// Maps a <see cref='Altask.Data.Model.AssetAlertUser'/> object to a <see cref='Altask.Data.Dto.AssetAlertUser'/> object.
    	/// </summary>
    	public static Altask.Data.Dto.AssetAlertUser ToDto(this Altask.Data.Model.AssetAlertUser entity) {
    		var dto = new Altask.Data.Dto.AssetAlertUser();
    		dto.Id = entity.Id;
    		dto.AssetAlertId = entity.AssetAlertId;
    		dto.UserId = entity.UserId;
    		dto.CreatedBy = entity.CreatedBy;
    		dto.CreatedOn = entity.CreatedOn;
    		dto.UpdatedBy = entity.UpdatedBy;
    		dto.UpdatedOn = entity.UpdatedOn;
    
    		if (entity.User != null) {
    			dto.User = entity.User.ToDto();
    		}
    
    		return dto;
    	}
    
    	/// <summary>
    	/// Maps all the non-primary key and tracking properties of a <see cref='Altask.Data.Dto.AssetAlertUser'/> object to a <see cref='Altask.Data.Model.AssetAlertUser'/> object.
    	/// </summary>
    	public static Altask.Data.Model.AssetAlertUser FromDto(this Altask.Data.Model.AssetAlertUser model, Altask.Data.Dto.AssetAlertUser entity) {
    		model.AssetAlertId = entity.AssetAlertId;
    		model.UserId = entity.UserId;
    		return model;
    	}
    }
}
