//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Altask.Data.Model
{
    using Altask.Data;
    using Newtonsoft.Json;
    using System;
    using System.Xml;
    using System;
    using System.Collections.Generic;
    
    public partial class AssetLog : ISupportsLongId, ISupportsAuthorFields
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssetLog()
        {
            this.Resolutions = new HashSet<AssetLogResolution>();
        }
    
    	/// <summary>
    	/// Gets or sets the Id of this <see cref='Altask.Data.Model.AssetLog'/>.
    	/// </summary>
        public long Id { get; set; }
    	/// <summary>
    	/// Gets or sets the AssetId of this <see cref='Altask.Data.Model.AssetLog'/>.
    	/// </summary>
        public int AssetId { get; set; }
    	/// <summary>
    	/// Gets or sets the AssetLogTypeId of this <see cref='Altask.Data.Model.AssetLog'/>.
    	/// </summary>
        public int AssetLogTypeId { get; set; }
    	/// <summary>
    	/// Gets or sets the Comment of this <see cref='Altask.Data.Model.AssetLog'/>.
    	/// </summary>
        public string Comment { get; set; }
    	/// <summary>
    	/// Gets or sets the Description of this <see cref='Altask.Data.Model.AssetLog'/>.
    	/// </summary>
        public string Description { get; set; }
    	/// <summary>
    	/// Gets or sets the Metadata of this <see cref='Altask.Data.Model.AssetLog'/>.
    	/// </summary>
        public string Metadata { get; set; }
    	/// <summary>
    	/// Gets or sets the CreatedBy of this <see cref='Altask.Data.Model.AssetLog'/>.
    	/// </summary>
        public string CreatedBy { get; set; }
    	/// <summary>
    	/// Gets or sets the CreatedOn of this <see cref='Altask.Data.Model.AssetLog'/>.
    	/// </summary>
        public System.DateTime CreatedOn { get; set; }
    	/// <summary>
    	/// Gets or sets the UpdatedBy of this <see cref='Altask.Data.Model.AssetLog'/>.
    	/// </summary>
        public string UpdatedBy { get; set; }
    	/// <summary>
    	/// Gets or sets the UpdatedOn of this <see cref='Altask.Data.Model.AssetLog'/>.
    	/// </summary>
        public System.DateTime UpdatedOn { get; set; }
    
        public virtual AssetLogType Type { get; set; }
        public virtual ICollection<AssetLogResolution> Resolutions { get; set; }
    }
    
    public static partial class Mapper {
    	/// <summary>
    	/// Maps a <see cref='Altask.Data.Model.AssetLog'/> object to a <see cref='Altask.Data.Dto.AssetLog'/> object.
    	/// </summary>
    	public static Altask.Data.Dto.AssetLog ToDto(this Altask.Data.Model.AssetLog entity) {
    		var dto = new Altask.Data.Dto.AssetLog();
    		dto.Id = entity.Id;
    		dto.AssetId = entity.AssetId;
    		dto.AssetLogTypeId = entity.AssetLogTypeId;
    		dto.Comment = entity.Comment;
    		dto.Description = entity.Description;
    		dto.Metadata = JsonConvert.DeserializeObject("{Properties: []}");
    
    		if (!string.IsNullOrEmpty(entity.Metadata)) {
    			try {
    				XmlDocument doc = new XmlDocument();
    				doc.LoadXml(entity.Metadata);
    				string json = Json.SerizlieXmlDocument(doc);
    				dto.Metadata = JsonConvert.DeserializeObject(json);
    			} catch(Exception) {}
    		}
    
    		dto.CreatedBy = entity.CreatedBy;
    		dto.CreatedOn = entity.CreatedOn;
    		dto.UpdatedBy = entity.UpdatedBy;
    		dto.UpdatedOn = entity.UpdatedOn;
    
    		if (entity.Type != null) {
    			dto.Type = entity.Type.ToDto();
    		}
    
    		dto.Resolutions = new List<Altask.Data.Dto.AssetLogResolution>();
    		
    		if (entity.Resolutions != null) {
    			foreach(var item in entity.Resolutions) {
    				dto.Resolutions.Add(item.ToDto());
    			}
    		}
    
    		return dto;
    	}
    
    	/// <summary>
    	/// Maps all the non-primary key and tracking properties of a <see cref='Altask.Data.Dto.AssetLog'/> object to a <see cref='Altask.Data.Model.AssetLog'/> object.
    	/// </summary>
    	public static Altask.Data.Model.AssetLog FromDto(this Altask.Data.Model.AssetLog model, Altask.Data.Dto.AssetLog entity) {
    		model.AssetId = entity.AssetId;
    		model.AssetLogTypeId = entity.AssetLogTypeId;
    		model.Comment = entity.Comment;
    		model.Description = entity.Description;
    		model.Metadata = string.Empty;
    
    		try {
    			model.Metadata = ((XmlDocument)JsonConvert.DeserializeXmlNode(entity.Metadata.ToString(), "Properties")).OuterXml;
    		} catch(Exception) {}
    
    		return model;
    	}
    }
}
