//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Altask.Data.Model
{
    using Altask.Data;
    using Newtonsoft.Json;
    using System;
    using System.Xml;
    using System;
    using System.Collections.Generic;
    
    public partial class AssetLogTypeAsset : ISupportsLongId, ISupportsAuthorFields
    {
    	/// <summary>
    	/// Gets or sets the Id of this <see cref='Altask.Data.Model.AssetLogTypeAsset'/>.
    	/// </summary>
        public long Id { get; set; }
    	/// <summary>
    	/// Gets or sets the AssetId of this <see cref='Altask.Data.Model.AssetLogTypeAsset'/>.
    	/// </summary>
        public int AssetId { get; set; }
    	/// <summary>
    	/// Gets or sets the AssetLogTypeId of this <see cref='Altask.Data.Model.AssetLogTypeAsset'/>.
    	/// </summary>
        public int AssetLogTypeId { get; set; }
    	/// <summary>
    	/// Gets or sets the CreatedBy of this <see cref='Altask.Data.Model.AssetLogTypeAsset'/>.
    	/// </summary>
        public string CreatedBy { get; set; }
    	/// <summary>
    	/// Gets or sets the CreatedOn of this <see cref='Altask.Data.Model.AssetLogTypeAsset'/>.
    	/// </summary>
        public System.DateTime CreatedOn { get; set; }
    	/// <summary>
    	/// Gets or sets the UpdatedBy of this <see cref='Altask.Data.Model.AssetLogTypeAsset'/>.
    	/// </summary>
        public string UpdatedBy { get; set; }
    	/// <summary>
    	/// Gets or sets the UpdatedOn of this <see cref='Altask.Data.Model.AssetLogTypeAsset'/>.
    	/// </summary>
        public System.DateTime UpdatedOn { get; set; }
    }
    
    public static partial class Mapper {
    	/// <summary>
    	/// Maps a <see cref='Altask.Data.Model.AssetLogTypeAsset'/> object to a <see cref='Altask.Data.Dto.AssetLogTypeAsset'/> object.
    	/// </summary>
    	public static Altask.Data.Dto.AssetLogTypeAsset ToDto(this Altask.Data.Model.AssetLogTypeAsset entity) {
    		var dto = new Altask.Data.Dto.AssetLogTypeAsset();
    		dto.Id = entity.Id;
    		dto.AssetId = entity.AssetId;
    		dto.AssetLogTypeId = entity.AssetLogTypeId;
    		dto.CreatedBy = entity.CreatedBy;
    		dto.CreatedOn = entity.CreatedOn;
    		dto.UpdatedBy = entity.UpdatedBy;
    		dto.UpdatedOn = entity.UpdatedOn;
    
    		return dto;
    	}
    
    	/// <summary>
    	/// Maps all the non-primary key and tracking properties of a <see cref='Altask.Data.Dto.AssetLogTypeAsset'/> object to a <see cref='Altask.Data.Model.AssetLogTypeAsset'/> object.
    	/// </summary>
    	public static Altask.Data.Model.AssetLogTypeAsset FromDto(this Altask.Data.Model.AssetLogTypeAsset model, Altask.Data.Dto.AssetLogTypeAsset entity) {
    		model.AssetId = entity.AssetId;
    		model.AssetLogTypeId = entity.AssetLogTypeId;
    		return model;
    	}
    }
}
