//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Altask.Data.Model
{
    using Altask.Data;
    using Newtonsoft.Json;
    using System;
    using System.Xml;
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleUser : ISupportsLongId, ISupportsAuthorFields
    {
    	/// <summary>
    	/// Gets or sets the Id of this <see cref='Altask.Data.Model.ScheduleUser'/>.
    	/// </summary>
        public long Id { get; set; }
    	/// <summary>
    	/// Gets or sets the ScheduleId of this <see cref='Altask.Data.Model.ScheduleUser'/>.
    	/// </summary>
        public long ScheduleId { get; set; }
    	/// <summary>
    	/// Gets or sets the UserId of this <see cref='Altask.Data.Model.ScheduleUser'/>.
    	/// </summary>
        public int UserId { get; set; }
    	/// <summary>
    	/// Gets or sets the ScheduleUserTypeId of this <see cref='Altask.Data.Model.ScheduleUser'/>.
    	/// </summary>
        public int ScheduleUserTypeId { get; set; }
    	/// <summary>
    	/// Gets or sets the CreatedBy of this <see cref='Altask.Data.Model.ScheduleUser'/>.
    	/// </summary>
        public string CreatedBy { get; set; }
    	/// <summary>
    	/// Gets or sets the CreatedOn of this <see cref='Altask.Data.Model.ScheduleUser'/>.
    	/// </summary>
        public System.DateTime CreatedOn { get; set; }
    	/// <summary>
    	/// Gets or sets the UpdatedBy of this <see cref='Altask.Data.Model.ScheduleUser'/>.
    	/// </summary>
        public string UpdatedBy { get; set; }
    	/// <summary>
    	/// Gets or sets the UpdatedOn of this <see cref='Altask.Data.Model.ScheduleUser'/>.
    	/// </summary>
        public System.DateTime UpdatedOn { get; set; }
    
        public virtual Schedule Schedule { get; set; }
        public virtual ScheduleUserType ScheduleUserType { get; set; }
        public virtual User User { get; set; }
    }
    
    public static partial class Mapper {
    	/// <summary>
    	/// Maps a <see cref='Altask.Data.Model.ScheduleUser'/> object to a <see cref='Altask.Data.Dto.ScheduleUser'/> object.
    	/// </summary>
    	/// <param name="includeLogs">Indicates whether to load any logs associated with the object when mapping.</param>
    	public static Altask.Data.Dto.ScheduleUser ToDto(this Altask.Data.Model.ScheduleUser entity, bool includeLogs = false) {
    		var dto = new Altask.Data.Dto.ScheduleUser();
    		dto.Id = entity.Id;
    		dto.ScheduleId = entity.ScheduleId;
    		dto.UserId = entity.UserId;
    		dto.ScheduleUserTypeId = entity.ScheduleUserTypeId;
    		dto.CreatedBy = entity.CreatedBy;
    		dto.CreatedOn = entity.CreatedOn;
    		dto.UpdatedBy = entity.UpdatedBy;
    		dto.UpdatedOn = entity.UpdatedOn;
    
    		if (entity.Schedule != null) {
    			dto.Schedule = entity.Schedule.ToDto();
    		}
    
    		if (entity.ScheduleUserType != null) {
    			dto.ScheduleUserType = entity.ScheduleUserType.ToDto();
    		}
    
    		if (entity.User != null) {
    			dto.User = entity.User.ToDto();
    		}
    
    		return dto;
    	}
    
    	/// <summary>
    	/// Maps all the non-primary key and tracking properties of a <see cref='Altask.Data.Dto.ScheduleUser'/> object to a <see cref='Altask.Data.Model.ScheduleUser'/> object.
    	/// </summary>
    	public static Altask.Data.Model.ScheduleUser FromDto(this Altask.Data.Model.ScheduleUser model, Altask.Data.Dto.ScheduleUser entity) {
    		model.ScheduleId = entity.ScheduleId;
    		model.UserId = entity.UserId;
    		model.ScheduleUserTypeId = entity.ScheduleUserTypeId;
    		return model;
    	}
    }
}
