//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace Altask.www {
    public partial class SignalRHub {
		internal static void NotifyOccurrenceLogCreate(Guid? clientId, Altask.Data.Dto.OccurrenceLog occurrenceLog) {
			if (!clientId.HasValue) {
				_context.Clients.All.notifyOccurrenceLogCreate(new { occurrenceLog = occurrenceLog });
			} else {
				SignalRConnection connection;

				if (_connections.TryGetValue(clientId.Value, out connection)) {
					_context.Clients.AllExcept(connection.ConnectionId).notifyOccurrenceLogCreate(new { connection = connection, occurrenceLog = occurrenceLog });
				} else {
					_context.Clients.All.notifyOccurrenceLogCreate(new { occurrenceLog = occurrenceLog });
				}
			}
		}

        internal static void NotifyOccurrenceLogUpdate(Guid? clientId, Altask.Data.Dto.OccurrenceLog occurrenceLog) {
            if (!clientId.HasValue) {
				_context.Clients.All.notifyOccurrenceLogUpdate(new { occurrenceLog = occurrenceLog });
			} else {
				SignalRConnection connection;

				if (_connections.TryGetValue(clientId.Value, out connection)) {
					_context.Clients.AllExcept(connection.ConnectionId).notifyOccurrenceLogUpdate(new { connection = connection, occurrenceLog = occurrenceLog });
				} else {
					_context.Clients.All.notifyOccurrenceLogCreate(new { occurrenceLog = occurrenceLog });
				}
			}
		}
	}
}
