//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace Altask.www {
    public partial class SignalRHub {
		internal static void NotifyAssetTypeCreate(Guid? clientId, Altask.Data.Dto.AssetType assetType) {
			if (!clientId.HasValue) {
				_context.Clients.All.notifyAssetTypeCreate(new { assetType = assetType });
			} else {
				SignalRConnection connection;

				if (_connections.TryGetValue(clientId.Value, out connection)) {
					_context.Clients.AllExcept(connection.ConnectionId).notifyAssetTypeCreate(new { connection = connection, assetType = assetType });
				} else {
					_context.Clients.All.notifyAssetTypeCreate(new { assetType = assetType });
				}
			}
		}

        internal static void NotifyAssetTypeUpdate(Guid? clientId, Altask.Data.Dto.AssetType assetType) {
            if (!clientId.HasValue) {
				_context.Clients.All.notifyAssetTypeUpdate(new { assetType = assetType });
			} else {
				SignalRConnection connection;

				if (_connections.TryGetValue(clientId.Value, out connection)) {
					_context.Clients.AllExcept(connection.ConnectionId).notifyAssetTypeUpdate(new { connection = connection, assetType = assetType });
				} else {
					_context.Clients.All.notifyAssetTypeCreate(new { assetType = assetType });
				}
			}
		}
	}
}
