//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace Altask.www {
    public partial class SignalRHub {
		internal static void NotifyScheduleUserCreate(Guid? clientId, Altask.Data.Dto.ScheduleUser scheduleUser) {
			if (!clientId.HasValue) {
				_context.Clients.All.notifyScheduleUserCreate(new { scheduleUser = scheduleUser });
			} else {
				SignalRConnection connection;

				if (_connections.TryGetValue(clientId.Value, out connection)) {
					_context.Clients.AllExcept(connection.ConnectionId).notifyScheduleUserCreate(new { connection = connection, scheduleUser = scheduleUser });
				} else {
					_context.Clients.All.notifyScheduleUserCreate(new { scheduleUser = scheduleUser });
				}
			}
		}

        internal static void NotifyScheduleUserUpdate(Guid? clientId, Altask.Data.Dto.ScheduleUser scheduleUser) {
            if (!clientId.HasValue) {
				_context.Clients.All.notifyScheduleUserUpdate(new { scheduleUser = scheduleUser });
			} else {
				SignalRConnection connection;

				if (_connections.TryGetValue(clientId.Value, out connection)) {
					_context.Clients.AllExcept(connection.ConnectionId).notifyScheduleUserUpdate(new { connection = connection, scheduleUser = scheduleUser });
				} else {
					_context.Clients.All.notifyScheduleUserCreate(new { scheduleUser = scheduleUser });
				}
			}
		}
	}
}
