//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace Altask.www {
    public partial class SignalRHub {
		internal static void NotifyScheduleUserTypeCreate(Guid? clientId, Altask.Data.Dto.ScheduleUserType scheduleUserType) {
			if (!clientId.HasValue) {
				_context.Clients.All.notifyScheduleUserTypeCreate(new { scheduleUserType = scheduleUserType });
			} else {
				SignalRConnection connection;

				if (_connections.TryGetValue(clientId.Value, out connection)) {
					_context.Clients.AllExcept(connection.ConnectionId).notifyScheduleUserTypeCreate(new { connection = connection, scheduleUserType = scheduleUserType });
				} else {
					_context.Clients.All.notifyScheduleUserTypeCreate(new { scheduleUserType = scheduleUserType });
				}
			}
		}

        internal static void NotifyScheduleUserTypeUpdate(Guid? clientId, Altask.Data.Dto.ScheduleUserType scheduleUserType) {
            if (!clientId.HasValue) {
				_context.Clients.All.notifyScheduleUserTypeUpdate(new { scheduleUserType = scheduleUserType });
			} else {
				SignalRConnection connection;

				if (_connections.TryGetValue(clientId.Value, out connection)) {
					_context.Clients.AllExcept(connection.ConnectionId).notifyScheduleUserTypeUpdate(new { connection = connection, scheduleUserType = scheduleUserType });
				} else {
					_context.Clients.All.notifyScheduleUserTypeCreate(new { scheduleUserType = scheduleUserType });
				}
			}
		}
	}
}
