//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace Altask.www {
    public partial class SignalRHub {
		internal static void NotifyScheduleAssetTypeCreate(Guid? clientId, Altask.Data.Dto.ScheduleAssetType scheduleAssetType) {
			if (!clientId.HasValue) {
				_context.Clients.All.notifyScheduleAssetTypeCreate(new { scheduleAssetType = scheduleAssetType });
			} else {
				SignalRConnection connection;

				if (_connections.TryGetValue(clientId.Value, out connection)) {
					_context.Clients.AllExcept(connection.ConnectionId).notifyScheduleAssetTypeCreate(new { connection = connection, scheduleAssetType = scheduleAssetType });
				} else {
					_context.Clients.All.notifyScheduleAssetTypeCreate(new { scheduleAssetType = scheduleAssetType });
				}
			}
		}

        internal static void NotifyScheduleAssetTypeUpdate(Guid? clientId, Altask.Data.Dto.ScheduleAssetType scheduleAssetType) {
            if (!clientId.HasValue) {
				_context.Clients.All.notifyScheduleAssetTypeUpdate(new { scheduleAssetType = scheduleAssetType });
			} else {
				SignalRConnection connection;

				if (_connections.TryGetValue(clientId.Value, out connection)) {
					_context.Clients.AllExcept(connection.ConnectionId).notifyScheduleAssetTypeUpdate(new { connection = connection, scheduleAssetType = scheduleAssetType });
				} else {
					_context.Clients.All.notifyScheduleAssetTypeCreate(new { scheduleAssetType = scheduleAssetType });
				}
			}
		}
	}
}
