//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace Altask.www {
    public partial class SignalRHub {
		internal static void NotifyManufacturerCreate(Guid? clientId, Altask.Data.Dto.Manufacturer manufacturer) {
			if (!clientId.HasValue) {
				_context.Clients.All.notifyManufacturerCreate(new { manufacturer = manufacturer });
			} else {
				SignalRConnection connection;

				if (_connections.TryGetValue(clientId.Value, out connection)) {
					_context.Clients.AllExcept(connection.ConnectionId).notifyManufacturerCreate(new { connection = connection, manufacturer = manufacturer });
				} else {
					_context.Clients.All.notifyManufacturerCreate(new { manufacturer = manufacturer });
				}
			}
		}

        internal static void NotifyManufacturerUpdate(Guid? clientId, Altask.Data.Dto.Manufacturer manufacturer) {
            if (!clientId.HasValue) {
				_context.Clients.All.notifyManufacturerUpdate(new { manufacturer = manufacturer });
			} else {
				SignalRConnection connection;

				if (_connections.TryGetValue(clientId.Value, out connection)) {
					_context.Clients.AllExcept(connection.ConnectionId).notifyManufacturerUpdate(new { connection = connection, manufacturer = manufacturer });
				} else {
					_context.Clients.All.notifyManufacturerCreate(new { manufacturer = manufacturer });
				}
			}
		}
	}
}
