//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace Altask.www {
    public partial class SignalRHub {
		internal static void NotifyTaskTypeCreate(Guid? clientId, Altask.Data.Dto.TaskType taskType) {
			if (!clientId.HasValue) {
				_context.Clients.All.notifyTaskTypeCreate(new { taskType = taskType });
			} else {
				SignalRConnection connection;

				if (_connections.TryGetValue(clientId.Value, out connection)) {
					_context.Clients.AllExcept(connection.ConnectionId).notifyTaskTypeCreate(new { connection = connection, taskType = taskType });
				} else {
					_context.Clients.All.notifyTaskTypeCreate(new { taskType = taskType });
				}
			}
		}

        internal static void NotifyTaskTypeUpdate(Guid? clientId, Altask.Data.Dto.TaskType taskType) {
            if (!clientId.HasValue) {
				_context.Clients.All.notifyTaskTypeUpdate(new { taskType = taskType });
			} else {
				SignalRConnection connection;

				if (_connections.TryGetValue(clientId.Value, out connection)) {
					_context.Clients.AllExcept(connection.ConnectionId).notifyTaskTypeUpdate(new { connection = connection, taskType = taskType });
				} else {
					_context.Clients.All.notifyTaskTypeCreate(new { taskType = taskType });
				}
			}
		}
	}
}
