//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace Altask.www {
    public partial class SignalRHub {
		internal static void NotifyUserLogCreate(Guid? clientId, Altask.Data.Dto.UserLog userLog) {
			if (!clientId.HasValue) {
				_context.Clients.All.notifyUserLogCreate(new { userLog = userLog });
			} else {
				SignalRConnection connection;

				if (_connections.TryGetValue(clientId.Value, out connection)) {
					_context.Clients.AllExcept(connection.ConnectionId).notifyUserLogCreate(new { connection = connection, userLog = userLog });
				} else {
					_context.Clients.All.notifyUserLogCreate(new { userLog = userLog });
				}
			}
		}

        internal static void NotifyUserLogUpdate(Guid? clientId, Altask.Data.Dto.UserLog userLog) {
            if (!clientId.HasValue) {
				_context.Clients.All.notifyUserLogUpdate(new { userLog = userLog });
			} else {
				SignalRConnection connection;

				if (_connections.TryGetValue(clientId.Value, out connection)) {
					_context.Clients.AllExcept(connection.ConnectionId).notifyUserLogUpdate(new { connection = connection, userLog = userLog });
				} else {
					_context.Clients.All.notifyUserLogCreate(new { userLog = userLog });
				}
			}
		}
	}
}
