//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace Altask.www {
    public partial class SignalRHub {
		internal static void NotifyAssetLogTypeCreate(Guid? clientId, Altask.Data.Dto.AssetLogType assetLogType) {
			if (!clientId.HasValue) {
				_context.Clients.All.notifyAssetLogTypeCreate(new { assetLogType = assetLogType });
			} else {
				SignalRConnection connection;

				if (_connections.TryGetValue(clientId.Value, out connection)) {
					_context.Clients.AllExcept(connection.ConnectionId).notifyAssetLogTypeCreate(new { connection = connection, assetLogType = assetLogType });
				} else {
					_context.Clients.All.notifyAssetLogTypeCreate(new { assetLogType = assetLogType });
				}
			}
		}

        internal static void NotifyAssetLogTypeUpdate(Guid? clientId, Altask.Data.Dto.AssetLogType assetLogType) {
            if (!clientId.HasValue) {
				_context.Clients.All.notifyAssetLogTypeUpdate(new { assetLogType = assetLogType });
			} else {
				SignalRConnection connection;

				if (_connections.TryGetValue(clientId.Value, out connection)) {
					_context.Clients.AllExcept(connection.ConnectionId).notifyAssetLogTypeUpdate(new { connection = connection, assetLogType = assetLogType });
				} else {
					_context.Clients.All.notifyAssetLogTypeCreate(new { assetLogType = assetLogType });
				}
			}
		}
	}
}
