//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace Altask.www {
    public partial class SignalRHub {
		internal static void NotifyRoleCreate(Guid? clientId, Altask.Data.Dto.Role role) {
			if (!clientId.HasValue) {
				_context.Clients.All.notifyRoleCreate(new { role = role });
			} else {
				SignalRConnection connection;

				if (_connections.TryGetValue(clientId.Value, out connection)) {
					_context.Clients.AllExcept(connection.ConnectionId).notifyRoleCreate(new { connection = connection, role = role });
				} else {
					_context.Clients.All.notifyRoleCreate(new { role = role });
				}
			}
		}

        internal static void NotifyRoleUpdate(Guid? clientId, Altask.Data.Dto.Role role) {
            if (!clientId.HasValue) {
				_context.Clients.All.notifyRoleUpdate(new { role = role });
			} else {
				SignalRConnection connection;

				if (_connections.TryGetValue(clientId.Value, out connection)) {
					_context.Clients.AllExcept(connection.ConnectionId).notifyRoleUpdate(new { connection = connection, role = role });
				} else {
					_context.Clients.All.notifyRoleCreate(new { role = role });
				}
			}
		}
	}
}
