//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace Altask.www {
    public partial class SignalRHub {
		internal static void NotifyDepartmentCreate(Guid? clientId, Altask.Data.Dto.Department department) {
			if (!clientId.HasValue) {
				_context.Clients.All.notifyDepartmentCreate(new { department = department });
			} else {
				SignalRConnection connection;

				if (_connections.TryGetValue(clientId.Value, out connection)) {
					_context.Clients.AllExcept(connection.ConnectionId).notifyDepartmentCreate(new { connection = connection, department = department });
				} else {
					_context.Clients.All.notifyDepartmentCreate(new { department = department });
				}
			}
		}

        internal static void NotifyDepartmentUpdate(Guid? clientId, Altask.Data.Dto.Department department) {
            if (!clientId.HasValue) {
				_context.Clients.All.notifyDepartmentUpdate(new { department = department });
			} else {
				SignalRConnection connection;

				if (_connections.TryGetValue(clientId.Value, out connection)) {
					_context.Clients.AllExcept(connection.ConnectionId).notifyDepartmentUpdate(new { connection = connection, department = department });
				} else {
					_context.Clients.All.notifyDepartmentCreate(new { department = department });
				}
			}
		}
	}
}
