//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace Altask.www {
    public partial class SignalRHub {
		internal static void NotifyTaskCategoryCreate(Guid? clientId, Altask.Data.Dto.TaskCategory taskCategory) {
			if (!clientId.HasValue) {
				_context.Clients.All.notifyTaskCategoryCreate(new { taskCategory = taskCategory });
			} else {
				SignalRConnection connection;

				if (_connections.TryGetValue(clientId.Value, out connection)) {
					_context.Clients.AllExcept(connection.ConnectionId).notifyTaskCategoryCreate(new { connection = connection, taskCategory = taskCategory });
				} else {
					_context.Clients.All.notifyTaskCategoryCreate(new { taskCategory = taskCategory });
				}
			}
		}

        internal static void NotifyTaskCategoryUpdate(Guid? clientId, Altask.Data.Dto.TaskCategory taskCategory) {
            if (!clientId.HasValue) {
				_context.Clients.All.notifyTaskCategoryUpdate(new { taskCategory = taskCategory });
			} else {
				SignalRConnection connection;

				if (_connections.TryGetValue(clientId.Value, out connection)) {
					_context.Clients.AllExcept(connection.ConnectionId).notifyTaskCategoryUpdate(new { connection = connection, taskCategory = taskCategory });
				} else {
					_context.Clients.All.notifyTaskCategoryCreate(new { taskCategory = taskCategory });
				}
			}
		}
	}
}
