//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Altask.www.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    /// <summary>
    ///	Represents a collection of properties on which you can filter a collection of <see cref="Altask.Data.Dto.AssetLogType"/> objects.
    /// </summary>
    public partial class AssetLogTypeListOptions : ListOptions<Altask.Data.Model.AssetLogType>
    {
    	/// <summary>
    	/// Indicates wheather to filter on the <see cref="Altask.Data.Dto.AssetLogType"/>.Active property.
    	/// </summary>
    	public bool? Active { get; set; }
    
    	/// <summary>
    	///	Creates a Predicate derived from the filter's Active property.
    	/// </summary>
    	private Expression<Func<Altask.Data.Model.AssetLogType, bool>> GetActivePredicate() {
    		if (Active.HasValue) {
    			var predicate = PredicateBuilder.True<Altask.Data.Model.AssetLogType>();
    			var value = Active.Value;
    			predicate = predicate.And(e => e.Active == value);
    			return predicate;
    		}
    		
    		return null;	
    	}
    		
    	/// <summary>
    	///	A comma delimited string representing one or more <see cref="Altask.Data.Dto.AssetLogType"/>.AssetLogTypeCategoryId values to filter on.
    	/// </summary>
    	public string AssetLogTypeCategoryIds { get; set; }
    
    	/// <summary>
    	///	Parses the AssetLogTypeCategoryIds property and returns a <see cref="System.Collections.Generic.List{Int32}"/> containing any <see cref="Altask.Data.Dto.AssetLogType"/>.AssetLogTypeCategoryId values to filter on.
    	/// </summary>
    	public List<Int32> GetAssetLogTypeCategoryIds() {
    		var list = new List<Int32>();
    		
    		if (AssetLogTypeCategoryIds != null) {
    			var items = AssetLogTypeCategoryIds.Split(',');
    
    			foreach(var item in items) {
    				Int32 parsed;
    
    				if (Int32.TryParse(item, out parsed)) {
    					list.Add(parsed);
    				}
    			}
    		}
    
    		return list;
    	}
    
    	/// <summary>
    	///	Creates a Predicate derived from the filter's AssetLogTypeCategoryIds property.
    	/// </summary>
    	private Expression<Func<Altask.Data.Model.AssetLogType, bool>> GetAssetLogTypeCategoryIdsPredicate() {
    		var values = GetAssetLogTypeCategoryIds();
    
    		if (values.Count > 0) {
    			var predicate = PredicateBuilder.False<Altask.Data.Model.AssetLogType>();
    
    			foreach(var item in values) {
    				var value = item;
    				predicate = predicate.Or(e => e.AssetLogTypeCategoryId == value);
    			}
    
    			return predicate;
    		}
    		
    		return null;	
    	}
    
    	/// <summary>
    	///	Creates a Predicate from the filter's specified properties which evaluates to true.
    	/// </summary>
    	public Expression<Func<Altask.Data.Model.AssetLogType, bool>> GetPredicate() {
    		var predicate = PredicateBuilder.True<Altask.Data.Model.AssetLogType>();
    		var custom = GetCustomPredicate();
    
            if (custom != null) {
                predicate = predicate.And(custom);
            }
    
    		var activePredicate = GetActivePredicate();
    
    		if (activePredicate != null) {
    			predicate = predicate.And(activePredicate);
    		}
    		var assetLogTypeCategoryIdsPredicate = GetAssetLogTypeCategoryIdsPredicate();
    
    		if (assetLogTypeCategoryIdsPredicate != null) {
    			predicate = predicate.And(assetLogTypeCategoryIdsPredicate);
    		}
    
    		return predicate;	
    	}
    }
}
