//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Altask.www.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    /// <summary>
    ///	Represents a collection of properties on which you can filter a collection of <see cref="Altask.Data.Dto.UserRole"/> objects.
    /// </summary>
    public partial class UserRoleListOptions : ListOptions<Altask.Data.Model.UserRole>
    {
    	/// <summary>
    	///	A comma delimited string representing one or more <see cref="Altask.Data.Dto.UserRole"/>.RoleId values to filter on.
    	/// </summary>
    	public string RoleIds { get; set; }
    
    	/// <summary>
    	///	Parses the RoleIds property and returns a <see cref="System.Collections.Generic.List{Int32}"/> containing any <see cref="Altask.Data.Dto.UserRole"/>.RoleId values to filter on.
    	/// </summary>
    	public List<Int32> GetRoleIds() {
    		var list = new List<Int32>();
    		
    		if (RoleIds != null) {
    			var items = RoleIds.Split(',');
    
    			foreach(var item in items) {
    				Int32 parsed;
    
    				if (Int32.TryParse(item, out parsed)) {
    					list.Add(parsed);
    				}
    			}
    		}
    
    		return list;
    	}
    
    	/// <summary>
    	///	Creates a Predicate derived from the filter's RoleIds property.
    	/// </summary>
    	private Expression<Func<Altask.Data.Model.UserRole, bool>> GetRoleIdsPredicate() {
    		var values = GetRoleIds();
    
    		if (values.Count > 0) {
    			var predicate = PredicateBuilder.False<Altask.Data.Model.UserRole>();
    
    			foreach(var item in values) {
    				var value = item;
    				predicate = predicate.Or(e => e.RoleId == value);
    			}
    
    			return predicate;
    		}
    		
    		return null;	
    	}
    
    	/// <summary>
    	///	Creates a Predicate from the filter's specified properties which evaluates to true.
    	/// </summary>
    	public Expression<Func<Altask.Data.Model.UserRole, bool>> GetPredicate() {
    		var predicate = PredicateBuilder.True<Altask.Data.Model.UserRole>();
    		var custom = GetCustomPredicate();
    
            if (custom != null) {
                predicate = predicate.And(custom);
            }
    
    		var roleIdsPredicate = GetRoleIdsPredicate();
    
    		if (roleIdsPredicate != null) {
    			predicate = predicate.And(roleIdsPredicate);
    		}
    
    		return predicate;	
    	}
    }
}
