//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Altask.Data.Dto
{
    using Altask.Data;
    using System;
    using System.Collections.Generic;
    
    public partial class Occurrence
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Occurrence()
        {
            this.Logs = new HashSet<OccurrenceLog>();
        }
    
    	/// <summary>
    	/// Gets or sets the Id of this <see cref='Altask.Data.Dto.Occurrence'/>.
    	/// </summary>
        public long Id { get; set; }
    	/// <summary>
    	/// Gets or sets the TaskId of this <see cref='Altask.Data.Dto.Occurrence'/>.
    	/// </summary>
        public long TaskId { get; set; }
    	/// <summary>
    	/// Gets or sets the ScheduleId of this <see cref='Altask.Data.Dto.Occurrence'/>.
    	/// </summary>
        public long ScheduleId { get; set; }
    	/// <summary>
    	/// Gets or sets the AssetId of this <see cref='Altask.Data.Dto.Occurrence'/>.
    	/// </summary>
        public Nullable<int> AssetId { get; set; }
    	/// <summary>
    	/// Gets or sets the UserId of this <see cref='Altask.Data.Dto.Occurrence'/>.
    	/// </summary>
        public Nullable<int> UserId { get; set; }
    	/// <summary>
    	/// Gets or sets the FormModel of this <see cref='Altask.Data.Dto.Occurrence'/>.
    	/// </summary>
        public string FormModel { get; set; }
    	/// <summary>
    	/// Gets or sets the XmlResults of this <see cref='Altask.Data.Dto.Occurrence'/>.
    	/// </summary>
        public string XmlResults { get; set; }
    	/// <summary>
    	/// Gets or sets the AsEarlyAsDate of this <see cref='Altask.Data.Dto.Occurrence'/>.
    	/// </summary>
        public Nullable<System.DateTime> AsEarlyAsDate { get; set; }
    	/// <summary>
    	/// Gets or sets the Date of this <see cref='Altask.Data.Dto.Occurrence'/>.
    	/// </summary>
        public System.DateTime Date { get; set; }
    	/// <summary>
    	/// Gets or sets the Dismissed of this <see cref='Altask.Data.Dto.Occurrence'/>.
    	/// </summary>
        public Nullable<bool> Dismissed { get; set; }
    	/// <summary>
    	/// Gets or sets the DismissedBy of this <see cref='Altask.Data.Dto.Occurrence'/>.
    	/// </summary>
        public string DismissedBy { get; set; }
    	/// <summary>
    	/// Gets or sets the DismissedOn of this <see cref='Altask.Data.Dto.Occurrence'/>.
    	/// </summary>
        public Nullable<System.DateTime> DismissedOn { get; set; }
    	/// <summary>
    	/// Gets or sets the Started of this <see cref='Altask.Data.Dto.Occurrence'/>.
    	/// </summary>
        public Nullable<bool> Started { get; set; }
    	/// <summary>
    	/// Gets or sets the StartedBy of this <see cref='Altask.Data.Dto.Occurrence'/>.
    	/// </summary>
        public string StartedBy { get; set; }
    	/// <summary>
    	/// Gets or sets the StartedOn of this <see cref='Altask.Data.Dto.Occurrence'/>.
    	/// </summary>
        public Nullable<System.DateTime> StartedOn { get; set; }
    	/// <summary>
    	/// Gets or sets the StoppedBy of this <see cref='Altask.Data.Dto.Occurrence'/>.
    	/// </summary>
        public string StoppedBy { get; set; }
    	/// <summary>
    	/// Gets or sets the StoppedOn of this <see cref='Altask.Data.Dto.Occurrence'/>.
    	/// </summary>
        public Nullable<System.DateTime> StoppedOn { get; set; }
    	/// <summary>
    	/// Gets or sets the ResumedBy of this <see cref='Altask.Data.Dto.Occurrence'/>.
    	/// </summary>
        public string ResumedBy { get; set; }
    	/// <summary>
    	/// Gets or sets the ResumedOn of this <see cref='Altask.Data.Dto.Occurrence'/>.
    	/// </summary>
        public Nullable<System.DateTime> ResumedOn { get; set; }
    	/// <summary>
    	/// Gets or sets the Completed of this <see cref='Altask.Data.Dto.Occurrence'/>.
    	/// </summary>
        public Nullable<bool> Completed { get; set; }
    	/// <summary>
    	/// Gets or sets the CompletedBy of this <see cref='Altask.Data.Dto.Occurrence'/>.
    	/// </summary>
        public string CompletedBy { get; set; }
    	/// <summary>
    	/// Gets or sets the CompletedOn of this <see cref='Altask.Data.Dto.Occurrence'/>.
    	/// </summary>
        public Nullable<System.DateTime> CompletedOn { get; set; }
    	/// <summary>
    	/// Gets or sets the TimeSpent of this <see cref='Altask.Data.Dto.Occurrence'/>.
    	/// </summary>
        public Nullable<int> TimeSpent { get; set; }
    	/// <summary>
    	/// Gets or sets the CreatedBy of this <see cref='Altask.Data.Dto.Occurrence'/>.
    	/// </summary>
        public string CreatedBy { get; set; }
    	/// <summary>
    	/// Gets or sets the CreatedOn of this <see cref='Altask.Data.Dto.Occurrence'/>.
    	/// </summary>
        public System.DateTime CreatedOn { get; set; }
    	/// <summary>
    	/// Gets or sets the UpdatedBy of this <see cref='Altask.Data.Dto.Occurrence'/>.
    	/// </summary>
        public string UpdatedBy { get; set; }
    	/// <summary>
    	/// Gets or sets the UpdatedOn of this <see cref='Altask.Data.Dto.Occurrence'/>.
    	/// </summary>
        public System.DateTime UpdatedOn { get; set; }
    
        public virtual Asset Asset { get; set; }
        public virtual Schedule Schedule { get; set; }
        public virtual Task Task { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<OccurrenceLog> Logs { get; set; }
    }
}
