//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Altask.Data.Dto
{
    using Altask.Data;
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
    	/// <summary>
    	/// Gets or sets the Id of this <see cref='Altask.Data.Dto.Role'/>.
    	/// </summary>
        public int Id { get; set; }
    	/// <summary>
    	/// Gets or sets the Name of this <see cref='Altask.Data.Dto.Role'/>.
    	/// </summary>
        public string Name { get; set; }
    }
}
