//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Altask.Data.Dto
{
    using Altask.Data;
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleAsset
    {
    	/// <summary>
    	/// Gets or sets the Id of this <see cref='Altask.Data.Dto.ScheduleAsset'/>.
    	/// </summary>
        public long Id { get; set; }
    	/// <summary>
    	/// Gets or sets the ScheduleId of this <see cref='Altask.Data.Dto.ScheduleAsset'/>.
    	/// </summary>
        public long ScheduleId { get; set; }
    	/// <summary>
    	/// Gets or sets the AssetId of this <see cref='Altask.Data.Dto.ScheduleAsset'/>.
    	/// </summary>
        public int AssetId { get; set; }
    	/// <summary>
    	/// Gets or sets the ScheduleAssetTypeId of this <see cref='Altask.Data.Dto.ScheduleAsset'/>.
    	/// </summary>
        public int ScheduleAssetTypeId { get; set; }
    	/// <summary>
    	/// Gets or sets the CreatedBy of this <see cref='Altask.Data.Dto.ScheduleAsset'/>.
    	/// </summary>
        public string CreatedBy { get; set; }
    	/// <summary>
    	/// Gets or sets the CreatedOn of this <see cref='Altask.Data.Dto.ScheduleAsset'/>.
    	/// </summary>
        public System.DateTime CreatedOn { get; set; }
    	/// <summary>
    	/// Gets or sets the UpdatedBy of this <see cref='Altask.Data.Dto.ScheduleAsset'/>.
    	/// </summary>
        public string UpdatedBy { get; set; }
    	/// <summary>
    	/// Gets or sets the UpdatedOn of this <see cref='Altask.Data.Dto.ScheduleAsset'/>.
    	/// </summary>
        public System.DateTime UpdatedOn { get; set; }
    
        public virtual Asset Asset { get; set; }
        public virtual ScheduleAssetType Type { get; set; }
    }
}
