//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Altask.Data.Dto
{
    using Altask.Data;
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
    	/// <summary>
    	/// Gets or sets the Id of this <see cref='Altask.Data.Dto.Setting'/>.
    	/// </summary>
        public int Id { get; set; }
    	/// <summary>
    	/// Gets or sets the Name of this <see cref='Altask.Data.Dto.Setting'/>.
    	/// </summary>
        public string Name { get; set; }
    	/// <summary>
    	/// Gets or sets the Area of this <see cref='Altask.Data.Dto.Setting'/>.
    	/// </summary>
        public string Area { get; set; }
    	/// <summary>
    	/// Gets or sets the Classification of this <see cref='Altask.Data.Dto.Setting'/>.
    	/// </summary>
        public string Classification { get; set; }
    	/// <summary>
    	/// Gets or sets the Value of this <see cref='Altask.Data.Dto.Setting'/>.
    	/// </summary>
        public string Value { get; set; }
    	/// <summary>
    	/// Gets or sets the CreatedBy of this <see cref='Altask.Data.Dto.Setting'/>.
    	/// </summary>
        public string CreatedBy { get; set; }
    	/// <summary>
    	/// Gets or sets the CreatedOn of this <see cref='Altask.Data.Dto.Setting'/>.
    	/// </summary>
        public System.DateTime CreatedOn { get; set; }
    	/// <summary>
    	/// Gets or sets the UpdatedBy of this <see cref='Altask.Data.Dto.Setting'/>.
    	/// </summary>
        public string UpdatedBy { get; set; }
    	/// <summary>
    	/// Gets or sets the UpdatedOn of this <see cref='Altask.Data.Dto.Setting'/>.
    	/// </summary>
        public System.DateTime UpdatedOn { get; set; }
    }
}
