//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Altask.Data.Dto
{
    using Altask.Data;
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.Schedules = new HashSet<Schedule>();
            this.Alerts = new HashSet<TaskAlert>();
        }
    
    	/// <summary>
    	/// Gets or sets the Id of this <see cref='Altask.Data.Dto.Task'/>.
    	/// </summary>
        public long Id { get; set; }
    	/// <summary>
    	/// Gets or sets the Active of this <see cref='Altask.Data.Dto.Task'/>.
    	/// </summary>
        public bool Active { get; set; }
    	/// <summary>
    	/// Gets or sets the TaskTypeId of this <see cref='Altask.Data.Dto.Task'/>.
    	/// </summary>
        public int TaskTypeId { get; set; }
    	/// <summary>
    	/// Gets or sets the TaskCategoryId of this <see cref='Altask.Data.Dto.Task'/>.
    	/// </summary>
        public int TaskCategoryId { get; set; }
    	/// <summary>
    	/// Gets or sets the FormId of this <see cref='Altask.Data.Dto.Task'/>.
    	/// </summary>
        public Nullable<int> FormId { get; set; }
    	/// <summary>
    	/// Gets or sets the Name of this <see cref='Altask.Data.Dto.Task'/>.
    	/// </summary>
        public string Name { get; set; }
    	/// <summary>
    	/// Gets or sets the Description of this <see cref='Altask.Data.Dto.Task'/>.
    	/// </summary>
        public string Description { get; set; }
    	/// <summary>
    	/// Gets or sets the IdleTimeout of this <see cref='Altask.Data.Dto.Task'/>.
    	/// </summary>
        public int IdleTimeout { get; set; }
    	/// <summary>
    	/// Gets or sets the Metadata of this <see cref='Altask.Data.Dto.Task'/>.
    	/// </summary>
        public object Metadata { get; set; }
    	/// <summary>
    	/// Gets or sets the CreatedBy of this <see cref='Altask.Data.Dto.Task'/>.
    	/// </summary>
        public string CreatedBy { get; set; }
    	/// <summary>
    	/// Gets or sets the CreatedOn of this <see cref='Altask.Data.Dto.Task'/>.
    	/// </summary>
        public System.DateTime CreatedOn { get; set; }
    	/// <summary>
    	/// Gets or sets the UpdatedBy of this <see cref='Altask.Data.Dto.Task'/>.
    	/// </summary>
        public string UpdatedBy { get; set; }
    	/// <summary>
    	/// Gets or sets the UpdatedOn of this <see cref='Altask.Data.Dto.Task'/>.
    	/// </summary>
        public System.DateTime UpdatedOn { get; set; }
    
        public virtual Form Form { get; set; }
        public virtual ICollection<Schedule> Schedules { get; set; }
        public virtual TaskCategory Category { get; set; }
        public virtual TaskType Type { get; set; }
        public virtual ICollection<TaskAlert> Alerts { get; set; }
    }
}
