//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Altask.Data.Dto
{
    using Altask.Data;
    using System;
    using System.Collections.Generic;
    
    public partial class TaskAlert
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaskAlert()
        {
            this.Logs = new HashSet<TaskAlertLog>();
            this.Users = new HashSet<TaskAlertUser>();
        }
    
    	/// <summary>
    	/// Gets or sets the Id of this <see cref='Altask.Data.Dto.TaskAlert'/>.
    	/// </summary>
        public long Id { get; set; }
    	/// <summary>
    	/// Gets or sets the Active of this <see cref='Altask.Data.Dto.TaskAlert'/>.
    	/// </summary>
        public bool Active { get; set; }
    	/// <summary>
    	/// Gets or sets the TaskId of this <see cref='Altask.Data.Dto.TaskAlert'/>.
    	/// </summary>
        public long TaskId { get; set; }
    	/// <summary>
    	/// Gets or sets the Name of this <see cref='Altask.Data.Dto.TaskAlert'/>.
    	/// </summary>
        public string Name { get; set; }
    	/// <summary>
    	/// Gets or sets the TimeN of this <see cref='Altask.Data.Dto.TaskAlert'/>.
    	/// </summary>
        public Nullable<int> TimeN { get; set; }
    	/// <summary>
    	/// Gets or sets the TimeUnit of this <see cref='Altask.Data.Dto.TaskAlert'/>.
    	/// </summary>
        public string TimeUnit { get; set; }
    	/// <summary>
    	/// Gets or sets the When of this <see cref='Altask.Data.Dto.TaskAlert'/>.
    	/// </summary>
        public string When { get; set; }
    	/// <summary>
    	/// Gets or sets the IfNot of this <see cref='Altask.Data.Dto.TaskAlert'/>.
    	/// </summary>
        public Nullable<bool> IfNot { get; set; }
    	/// <summary>
    	/// Gets or sets the IfStatus of this <see cref='Altask.Data.Dto.TaskAlert'/>.
    	/// </summary>
        public string IfStatus { get; set; }
    	/// <summary>
    	/// Gets or sets the Metadata of this <see cref='Altask.Data.Dto.TaskAlert'/>.
    	/// </summary>
        public object Metadata { get; set; }
    	/// <summary>
    	/// Gets or sets the CreatedBy of this <see cref='Altask.Data.Dto.TaskAlert'/>.
    	/// </summary>
        public string CreatedBy { get; set; }
    	/// <summary>
    	/// Gets or sets the CreatedOn of this <see cref='Altask.Data.Dto.TaskAlert'/>.
    	/// </summary>
        public System.DateTime CreatedOn { get; set; }
    	/// <summary>
    	/// Gets or sets the UpdatedBy of this <see cref='Altask.Data.Dto.TaskAlert'/>.
    	/// </summary>
        public string UpdatedBy { get; set; }
    	/// <summary>
    	/// Gets or sets the UpdatedOn of this <see cref='Altask.Data.Dto.TaskAlert'/>.
    	/// </summary>
        public System.DateTime UpdatedOn { get; set; }
    
        public virtual ICollection<TaskAlertLog> Logs { get; set; }
        public virtual ICollection<TaskAlertUser> Users { get; set; }
    }
}
