//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Altask.www.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Linq;
    using System.Threading.Tasks;
    using System.Web.Mvc;
    using System.Xml;
    using Altask.www.Models;
    using Data.Model;
    
    [Authorize]
    public partial class AssetLogController : BaseController<Altask.Data.Model.AssetLog, Altask.Data.Dto.AssetLog>
    {
    	/// <summary>
    	/// Constructor
    	/// </summary>
    	public AssetLogController() : base() {
    	
    	}
    
    	/// <summary>
    	/// Constructor
    	/// </summary>
    	/// <param name="userManager">The application user manager used in this application. UserManager is defined in ASP.NET Identity and is used by the application.</param>
    	/// <param name="signInManager">The application sign-in manager which is used in this application.</param>
    	public AssetLogController(ApplicationUserManager userManager, ApplicationSignInManager signInManager) : base(userManager, signInManager) {
    
    	}
    
    	[HttpPost]
    	[JsonNetFilter]
    	/// <summary>
    	/// Create a <see cref="Altask.Data.Model.AssetLog"/>.
    	/// </summary>
    	/// <param name="assetLog"></param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> Create(Altask.Data.Dto.AssetLog assetLog) {
    		ThrowIfDisposed();
    
    		if (!ModelState.IsValid) {
    			return BadRequest(ModelState);
    		}
    
    		var newAssetLog = new Altask.Data.Model.AssetLog().FromDto(assetLog);
    		Context.AssetLogs.Add(newAssetLog);
    		BeforeCreate(newAssetLog, assetLog);
    		var result = await Context.SaveChangesAsync();
    		Context.Entry(newAssetLog).Collection(e => e.Resolutions).Load();
    		Context.Entry(newAssetLog).Reference(e => e.Type).Load();
        
        	if (result.Succeeded) {
    			await AfterCreateAsync(newAssetLog);
    			return Ok(new { assetLog = newAssetLog.ToDto() });
        	} else {
        		return BadRequest(result);
        	}
    	}
    
    	[HttpGet]
    	[JsonNetFilter]
    	/// <summary>
    	/// Returns a <see cref="Altask.Data.Model.AssetLog"/> having the specified ID.
    	/// </summary>
    	/// <param name="id">The ID of the <see cref="Altask.Data.Model.AssetLog"/>.</param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> FindById(long id) {
    		ThrowIfDisposed();
    		var assetLog = await Context.AssetLogs.FindAsync(id);
    		return Ok(new { assetLog = assetLog.ToDto() }, JsonRequestBehavior.AllowGet);
    	}
    
    	[HttpGet]
    	[JsonNetFilter]
    	/// <summary>
    	/// Returns a collection of <see cref="Altask.Data.Model.AssetLog"/> objects matching the specified filter.
    	/// </summary>
    	/// <param name="filter">A <see cref="Altask.www.Models.AssetLogListOptions"/> object on which to filter.</param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> List(AssetLogListOptions filter) {
    		ThrowIfDisposed();
    
    		if (filter == null) {
    			filter = new AssetLogListOptions();
    		}
    
    		var dtoAssetLogs = new List<Altask.Data.Dto.AssetLog>();
    		var assetLog = await Context.AssetLogs.AsNoTracking().Where(filter.GetPredicate())
    			.Include(e => e.Type)
    			.Include(e => e.Resolutions)
    			.ToListAsync();
    
    		foreach(var item in assetLog) {
    			dtoAssetLogs.Add(item.ToDto());
    		}
    
    		return Ok(new { assetLogs = dtoAssetLogs }, JsonRequestBehavior.AllowGet);
    	}
    
    	[HttpPost]
    	[JsonNetFilter]
    	/// <summary>
    	/// Updates the specified <see cref="Altask.Data.Model.AssetLog"/>.
    	/// </summary>
    	/// <param name="assetLog"></param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> Update(Altask.Data.Dto.AssetLog assetLog) {
    		ThrowIfDisposed();
    
    		if (!ModelState.IsValid) {
    			return BadRequest(ModelState);
    		}
    
    		var assetLogEntity = await Context.AssetLogs.FindAsync(assetLog.Id);
    
    		if (assetLogEntity == null) {
    			return BadRequest(ErrorDescriber.DoesNotExist("AssetLog"));
    		}
    
    		assetLogEntity.FromDto(assetLog);
    		Context.Entry(assetLogEntity).State = EntityState.Modified;
    		BeforeUpdate(assetLogEntity, assetLog);
    		var result = await Context.SaveChangesAsync();
    		Context.Entry(assetLogEntity).Collection(e => e.Resolutions).Load();
    		Context.Entry(assetLogEntity).Reference(e => e.Type).Load();
        
        	if (result.Succeeded) {
    			await AfterUpdateAsync(assetLogEntity);
    			return Ok(new { assetLog = assetLogEntity.ToDto() });
        	} else {
        		return BadRequest(result);
        	}
    	}
    }
}
