//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Altask.www.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Linq;
    using System.Threading.Tasks;
    using System.Web.Mvc;
    using System.Xml;
    using Altask.www.Models;
    using Data.Model;
    
    [Authorize]
    public partial class DepartmentController : BaseController<Altask.Data.Model.Department, Altask.Data.Dto.Department>
    {
    	/// <summary>
    	/// Constructor
    	/// </summary>
    	public DepartmentController() : base() {
    	
    	}
    
    	/// <summary>
    	/// Constructor
    	/// </summary>
    	/// <param name="userManager">The application user manager used in this application. UserManager is defined in ASP.NET Identity and is used by the application.</param>
    	/// <param name="signInManager">The application sign-in manager which is used in this application.</param>
    	public DepartmentController(ApplicationUserManager userManager, ApplicationSignInManager signInManager) : base(userManager, signInManager) {
    
    	}
    
    	[HttpPost]
    	[JsonNetFilter]
    	/// <summary>
    	/// Create a <see cref="Altask.Data.Model.Department"/>.
    	/// </summary>
    	/// <param name="department"></param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> Create(Altask.Data.Dto.Department department) {
    		ThrowIfDisposed();
    
    		if (!ModelState.IsValid) {
    			return BadRequest(ModelState);
    		}
    
    		var newDepartment = new Altask.Data.Model.Department().FromDto(department);
    		Context.Departments.Add(newDepartment);
    		BeforeCreate(newDepartment, department);
    		var result = await Context.SaveChangesAsync();
    		Context.Entry(newDepartment).Collection(e => e.Assets).Load();
        
        	if (result.Succeeded) {
    			await AfterCreateAsync(newDepartment);
    			return Ok(new { department = newDepartment.ToDto() });
        	} else {
        		return BadRequest(result);
        	}
    	}
    
    	[HttpGet]
    	[JsonNetFilter]
    	/// <summary>
    	/// Returns a <see cref="Altask.Data.Model.Department"/> having the specified ID.
    	/// </summary>
    	/// <param name="id">The ID of the <see cref="Altask.Data.Model.Department"/>.</param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> FindById(int id) {
    		ThrowIfDisposed();
    		var department = await Context.Departments.FindAsync(id);
    		return Ok(new { department = department.ToDto() }, JsonRequestBehavior.AllowGet);
    	}
    
    	[HttpGet]
    	[JsonNetFilter]
    	/// <summary>
    	/// Returns a collection of <see cref="Altask.Data.Model.Department"/> objects matching the specified filter.
    	/// </summary>
    	/// <param name="filter">A <see cref="Altask.www.Models.DepartmentListOptions"/> object on which to filter.</param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> List(DepartmentListOptions filter) {
    		ThrowIfDisposed();
    
    		if (filter == null) {
    			filter = new DepartmentListOptions();
    		}
    
    		var dtoDepartments = new List<Altask.Data.Dto.Department>();
    		var department = await Context.Departments.AsNoTracking().Where(filter.GetPredicate())
    			.Include(e => e.Assets)
    			.ToListAsync();
    
    		foreach(var item in department) {
    			dtoDepartments.Add(item.ToDto());
    		}
    
    		return Ok(new { departments = dtoDepartments }, JsonRequestBehavior.AllowGet);
    	}
    
    	[HttpPost]
    	[JsonNetFilter]
    	/// <summary>
    	/// Updates the specified <see cref="Altask.Data.Model.Department"/>.
    	/// </summary>
    	/// <param name="department"></param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> Update(Altask.Data.Dto.Department department) {
    		ThrowIfDisposed();
    
    		if (!ModelState.IsValid) {
    			return BadRequest(ModelState);
    		}
    
    		var departmentEntity = await Context.Departments.FindAsync(department.Id);
    
    		if (departmentEntity == null) {
    			return BadRequest(ErrorDescriber.DoesNotExist("Department"));
    		}
    
    		departmentEntity.FromDto(department);
    		Context.Entry(departmentEntity).State = EntityState.Modified;
    		BeforeUpdate(departmentEntity, department);
    		var result = await Context.SaveChangesAsync();
    		Context.Entry(departmentEntity).Collection(e => e.Assets).Load();
        
        	if (result.Succeeded) {
    			await AfterUpdateAsync(departmentEntity);
    			return Ok(new { department = departmentEntity.ToDto() });
        	} else {
        		return BadRequest(result);
        	}
    	}
    }
}
