//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Altask.www.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Linq;
    using System.Threading.Tasks;
    using System.Web.Mvc;
    using System.Xml;
    using Altask.www.Models;
    using Data.Model;
    
    [Authorize]
    public partial class FormLogController : BaseController<Altask.Data.Model.FormLog, Altask.Data.Dto.FormLog>
    {
    	/// <summary>
    	/// Constructor
    	/// </summary>
    	public FormLogController() : base() {
    	
    	}
    
    	/// <summary>
    	/// Constructor
    	/// </summary>
    	/// <param name="userManager">The application user manager used in this application. UserManager is defined in ASP.NET Identity and is used by the application.</param>
    	/// <param name="signInManager">The application sign-in manager which is used in this application.</param>
    	public FormLogController(ApplicationUserManager userManager, ApplicationSignInManager signInManager) : base(userManager, signInManager) {
    
    	}
    
    	[HttpPost]
    	[JsonNetFilter]
    	/// <summary>
    	/// Create a <see cref="Altask.Data.Model.FormLog"/>.
    	/// </summary>
    	/// <param name="formLog"></param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> Create(Altask.Data.Dto.FormLog formLog) {
    		ThrowIfDisposed();
    
    		if (!ModelState.IsValid) {
    			return BadRequest(ModelState);
    		}
    
    		var newFormLog = new Altask.Data.Model.FormLog().FromDto(formLog);
    		Context.FormLogs.Add(newFormLog);
    		BeforeCreate(newFormLog, formLog);
    		var result = await Context.SaveChangesAsync();
        
        	if (result.Succeeded) {
    			await AfterCreateAsync(newFormLog);
    			return Ok(new { formLog = newFormLog.ToDto() });
        	} else {
        		return BadRequest(result);
        	}
    	}
    
    	[HttpGet]
    	[JsonNetFilter]
    	/// <summary>
    	/// Returns a <see cref="Altask.Data.Model.FormLog"/> having the specified ID.
    	/// </summary>
    	/// <param name="id">The ID of the <see cref="Altask.Data.Model.FormLog"/>.</param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> FindById(long id) {
    		ThrowIfDisposed();
    		var formLog = await Context.FormLogs.FindAsync(id);
    		return Ok(new { formLog = formLog.ToDto() }, JsonRequestBehavior.AllowGet);
    	}
    
    	[HttpGet]
    	[JsonNetFilter]
    	/// <summary>
    	/// Returns a collection of <see cref="Altask.Data.Model.FormLog"/> objects.
    	/// </summary>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> List() {
    		ThrowIfDisposed();
    		var dtoFormLogs = new List<Altask.Data.Dto.FormLog>();
    		var formLog = await Context.FormLogs.ToListAsync();
    
    		foreach(var item in formLog) {
    			dtoFormLogs.Add(item.ToDto());
    		}
    
    		return Ok(new { formLogs = dtoFormLogs }, JsonRequestBehavior.AllowGet);
    	}
    
    	[HttpPost]
    	[JsonNetFilter]
    	/// <summary>
    	/// Updates the specified <see cref="Altask.Data.Model.FormLog"/>.
    	/// </summary>
    	/// <param name="formLog"></param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> Update(Altask.Data.Dto.FormLog formLog) {
    		ThrowIfDisposed();
    
    		if (!ModelState.IsValid) {
    			return BadRequest(ModelState);
    		}
    
    		var formLogEntity = await Context.FormLogs.FindAsync(formLog.Id);
    
    		if (formLogEntity == null) {
    			return BadRequest(ErrorDescriber.DoesNotExist("FormLog"));
    		}
    
    		formLogEntity.FromDto(formLog);
    		Context.Entry(formLogEntity).State = EntityState.Modified;
    		BeforeUpdate(formLogEntity, formLog);
    		var result = await Context.SaveChangesAsync();
        
        	if (result.Succeeded) {
    			await AfterUpdateAsync(formLogEntity);
    			return Ok(new { formLog = formLogEntity.ToDto() });
        	} else {
        		return BadRequest(result);
        	}
    	}
    }
}
