//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Altask.www.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Linq;
    using System.Threading.Tasks;
    using System.Web.Mvc;
    using System.Xml;
    using Altask.www.Models;
    using Data.Model;
    
    [Authorize]
    public partial class FormController : BaseController<Altask.Data.Model.Form, Altask.Data.Dto.Form>
    {
    	/// <summary>
    	/// Constructor
    	/// </summary>
    	public FormController() : base() {
    	
    	}
    
    	/// <summary>
    	/// Constructor
    	/// </summary>
    	/// <param name="userManager">The application user manager used in this application. UserManager is defined in ASP.NET Identity and is used by the application.</param>
    	/// <param name="signInManager">The application sign-in manager which is used in this application.</param>
    	public FormController(ApplicationUserManager userManager, ApplicationSignInManager signInManager) : base(userManager, signInManager) {
    
    	}
    
    	[HttpPost]
    	[JsonNetFilter]
    	/// <summary>
    	/// Create a <see cref="Altask.Data.Model.Form"/>.
    	/// </summary>
    	/// <param name="form"></param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> Create(Altask.Data.Dto.Form form) {
    		ThrowIfDisposed();
    
    		if (!ModelState.IsValid) {
    			return BadRequest(ModelState);
    		}
    
    		var newForm = new Altask.Data.Model.Form().FromDto(form);
    		Context.Forms.Add(newForm);
    		BeforeCreate(newForm, form);
    		var result = await Context.SaveChangesAsync();
        
        	if (result.Succeeded) {
    			await AfterCreateAsync(newForm);
    			return Ok(new { form = newForm.ToDto() });
        	} else {
        		return BadRequest(result);
        	}
    	}
    
    	[HttpGet]
    	[JsonNetFilter]
    	/// <summary>
    	/// Returns a <see cref="Altask.Data.Model.Form"/> having the specified ID.
    	/// </summary>
    	/// <param name="id">The ID of the <see cref="Altask.Data.Model.Form"/>.</param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> FindById(int id) {
    		ThrowIfDisposed();
    		var form = await Context.Forms.FindAsync(id);
    		return Ok(new { form = form.ToDto() }, JsonRequestBehavior.AllowGet);
    	}
    
    	[HttpGet]
    	[JsonNetFilter]
    	/// <summary>
    	/// Returns a collection of <see cref="Altask.Data.Model.Form"/> objects matching the specified filter.
    	/// </summary>
    	/// <param name="filter">A <see cref="Altask.www.Models.FormListOptions"/> object on which to filter.</param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> List(FormListOptions filter) {
    		ThrowIfDisposed();
    
    		if (filter == null) {
    			filter = new FormListOptions();
    		}
    
    		var dtoForms = new List<Altask.Data.Dto.Form>();
    		var form = await Context.Forms.AsNoTracking().Where(filter.GetPredicate())
    			.ToListAsync();
    
    		foreach(var item in form) {
    			dtoForms.Add(item.ToDto());
    		}
    
    		return Ok(new { forms = dtoForms }, JsonRequestBehavior.AllowGet);
    	}
    
    	[HttpPost]
    	[JsonNetFilter]
    	/// <summary>
    	/// Updates the specified <see cref="Altask.Data.Model.Form"/>.
    	/// </summary>
    	/// <param name="form"></param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> Update(Altask.Data.Dto.Form form) {
    		ThrowIfDisposed();
    
    		if (!ModelState.IsValid) {
    			return BadRequest(ModelState);
    		}
    
    		var formEntity = await Context.Forms.FindAsync(form.Id);
    
    		if (formEntity == null) {
    			return BadRequest(ErrorDescriber.DoesNotExist("Form"));
    		}
    
    		formEntity.FromDto(form);
    		Context.Entry(formEntity).State = EntityState.Modified;
    		BeforeUpdate(formEntity, form);
    		var result = await Context.SaveChangesAsync();
        
        	if (result.Succeeded) {
    			await AfterUpdateAsync(formEntity);
    			return Ok(new { form = formEntity.ToDto() });
        	} else {
        		return BadRequest(result);
        	}
    	}
    }
}
