//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Altask.www.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Linq;
    using System.Threading.Tasks;
    using System.Web.Mvc;
    using System.Xml;
    using Altask.www.Models;
    using Data.Model;
    
    [Authorize]
    public partial class ManufacturerController : BaseController<Altask.Data.Model.Manufacturer, Altask.Data.Dto.Manufacturer>
    {
    	/// <summary>
    	/// Constructor
    	/// </summary>
    	public ManufacturerController() : base() {
    	
    	}
    
    	/// <summary>
    	/// Constructor
    	/// </summary>
    	/// <param name="userManager">The application user manager used in this application. UserManager is defined in ASP.NET Identity and is used by the application.</param>
    	/// <param name="signInManager">The application sign-in manager which is used in this application.</param>
    	public ManufacturerController(ApplicationUserManager userManager, ApplicationSignInManager signInManager) : base(userManager, signInManager) {
    
    	}
    
    	[HttpPost]
    	[JsonNetFilter]
    	/// <summary>
    	/// Create a <see cref="Altask.Data.Model.Manufacturer"/>.
    	/// </summary>
    	/// <param name="manufacturer"></param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> Create(Altask.Data.Dto.Manufacturer manufacturer) {
    		ThrowIfDisposed();
    
    		if (!ModelState.IsValid) {
    			return BadRequest(ModelState);
    		}
    
    		var newManufacturer = new Altask.Data.Model.Manufacturer().FromDto(manufacturer);
    		Context.Manufacturers.Add(newManufacturer);
    		BeforeCreate(newManufacturer, manufacturer);
    		var result = await Context.SaveChangesAsync();
        
        	if (result.Succeeded) {
    			await AfterCreateAsync(newManufacturer);
    			return Ok(new { manufacturer = newManufacturer.ToDto() });
        	} else {
        		return BadRequest(result);
        	}
    	}
    
    	[HttpGet]
    	[JsonNetFilter]
    	/// <summary>
    	/// Returns a <see cref="Altask.Data.Model.Manufacturer"/> having the specified ID.
    	/// </summary>
    	/// <param name="id">The ID of the <see cref="Altask.Data.Model.Manufacturer"/>.</param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> FindById(int id) {
    		ThrowIfDisposed();
    		var manufacturer = await Context.Manufacturers.FindAsync(id);
    		return Ok(new { manufacturer = manufacturer.ToDto() }, JsonRequestBehavior.AllowGet);
    	}
    
    	[HttpGet]
    	[JsonNetFilter]
    	/// <summary>
    	/// Returns a collection of <see cref="Altask.Data.Model.Manufacturer"/> objects matching the specified filter.
    	/// </summary>
    	/// <param name="filter">A <see cref="Altask.www.Models.ManufacturerListOptions"/> object on which to filter.</param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> List(ManufacturerListOptions filter) {
    		ThrowIfDisposed();
    
    		if (filter == null) {
    			filter = new ManufacturerListOptions();
    		}
    
    		var dtoManufacturers = new List<Altask.Data.Dto.Manufacturer>();
    		var manufacturer = await Context.Manufacturers.AsNoTracking().Where(filter.GetPredicate())
    			.ToListAsync();
    
    		foreach(var item in manufacturer) {
    			dtoManufacturers.Add(item.ToDto());
    		}
    
    		return Ok(new { manufacturers = dtoManufacturers }, JsonRequestBehavior.AllowGet);
    	}
    
    	[HttpPost]
    	[JsonNetFilter]
    	/// <summary>
    	/// Updates the specified <see cref="Altask.Data.Model.Manufacturer"/>.
    	/// </summary>
    	/// <param name="manufacturer"></param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> Update(Altask.Data.Dto.Manufacturer manufacturer) {
    		ThrowIfDisposed();
    
    		if (!ModelState.IsValid) {
    			return BadRequest(ModelState);
    		}
    
    		var manufacturerEntity = await Context.Manufacturers.FindAsync(manufacturer.Id);
    
    		if (manufacturerEntity == null) {
    			return BadRequest(ErrorDescriber.DoesNotExist("Manufacturer"));
    		}
    
    		manufacturerEntity.FromDto(manufacturer);
    		Context.Entry(manufacturerEntity).State = EntityState.Modified;
    		BeforeUpdate(manufacturerEntity, manufacturer);
    		var result = await Context.SaveChangesAsync();
        
        	if (result.Succeeded) {
    			await AfterUpdateAsync(manufacturerEntity);
    			return Ok(new { manufacturer = manufacturerEntity.ToDto() });
        	} else {
        		return BadRequest(result);
        	}
    	}
    }
}
