//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Altask.www.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Linq;
    using System.Threading.Tasks;
    using System.Web.Mvc;
    using System.Xml;
    using Altask.www.Models;
    using Data.Model;
    
    [Authorize]
    public partial class OccurrenceController : BaseController<Altask.Data.Model.Occurrence, Altask.Data.Dto.Occurrence>
    {
    	/// <summary>
    	/// Constructor
    	/// </summary>
    	public OccurrenceController() : base() {
    	
    	}
    
    	/// <summary>
    	/// Constructor
    	/// </summary>
    	/// <param name="userManager">The application user manager used in this application. UserManager is defined in ASP.NET Identity and is used by the application.</param>
    	/// <param name="signInManager">The application sign-in manager which is used in this application.</param>
    	public OccurrenceController(ApplicationUserManager userManager, ApplicationSignInManager signInManager) : base(userManager, signInManager) {
    
    	}
    
    	[HttpPost]
    	[JsonNetFilter]
    	/// <summary>
    	/// Create a <see cref="Altask.Data.Model.Occurrence"/>.
    	/// </summary>
    	/// <param name="occurrence"></param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> Create(Altask.Data.Dto.Occurrence occurrence) {
    		ThrowIfDisposed();
    
    		if (!ModelState.IsValid) {
    			return BadRequest(ModelState);
    		}
    
    		var newOccurrence = new Altask.Data.Model.Occurrence().FromDto(occurrence);
    		Context.Occurrences.Add(newOccurrence);
    		BeforeCreate(newOccurrence, occurrence);
    		var result = await Context.SaveChangesAsync();
    		Context.Entry(newOccurrence).Reference(e => e.Asset).Load();
    		Context.Entry(newOccurrence).Reference(e => e.Schedule).Load();
    		Context.Entry(newOccurrence).Reference(e => e.Task).Load();
    		Context.Entry(newOccurrence).Reference(e => e.User).Load();
        
        	if (result.Succeeded) {
    			await AfterCreateAsync(newOccurrence);
    			return Ok(new { occurrence = newOccurrence.ToDto() });
        	} else {
        		return BadRequest(result);
        	}
    	}
    
    	[HttpGet]
    	[JsonNetFilter]
    	/// <summary>
    	/// Returns a <see cref="Altask.Data.Model.Occurrence"/> having the specified ID.
    	/// </summary>
    	/// <param name="id">The ID of the <see cref="Altask.Data.Model.Occurrence"/>.</param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> FindById(long id) {
    		ThrowIfDisposed();
    		var occurrence = await Context.Occurrences.FindAsync(id);
    		return Ok(new { occurrence = occurrence.ToDto() }, JsonRequestBehavior.AllowGet);
    	}
    
    	[HttpGet]
    	[JsonNetFilter]
    	/// <summary>
    	/// Returns a collection of <see cref="Altask.Data.Model.Occurrence"/> objects matching the specified filter.
    	/// </summary>
    	/// <param name="filter">A <see cref="Altask.www.Models.OccurrenceListOptions"/> object on which to filter.</param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> List(OccurrenceListOptions filter) {
    		ThrowIfDisposed();
    
    		if (filter == null) {
    			filter = new OccurrenceListOptions();
    		}
    
    		var dtoOccurrences = new List<Altask.Data.Dto.Occurrence>();
    		var occurrence = await Context.Occurrences.AsNoTracking().Where(filter.GetPredicate())
    			.Include(e => e.Asset)
    			.Include(e => e.Schedule)
    			.Include(e => e.Task)
    			.Include(e => e.User)
    			.ToListAsync();
    
    		foreach(var item in occurrence) {
    			dtoOccurrences.Add(item.ToDto());
    		}
    
    		return Ok(new { occurrences = dtoOccurrences }, JsonRequestBehavior.AllowGet);
    	}
    
    	[HttpPost]
    	[JsonNetFilter]
    	/// <summary>
    	/// Updates the specified <see cref="Altask.Data.Model.Occurrence"/>.
    	/// </summary>
    	/// <param name="occurrence"></param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> Update(Altask.Data.Dto.Occurrence occurrence) {
    		ThrowIfDisposed();
    
    		if (!ModelState.IsValid) {
    			return BadRequest(ModelState);
    		}
    
    		var occurrenceEntity = await Context.Occurrences.FindAsync(occurrence.Id);
    
    		if (occurrenceEntity == null) {
    			return BadRequest(ErrorDescriber.DoesNotExist("Occurrence"));
    		}
    
    		occurrenceEntity.FromDto(occurrence);
    		Context.Entry(occurrenceEntity).State = EntityState.Modified;
    		BeforeUpdate(occurrenceEntity, occurrence);
    		var result = await Context.SaveChangesAsync();
    		Context.Entry(occurrenceEntity).Reference(e => e.Asset).Load();
    		Context.Entry(occurrenceEntity).Reference(e => e.Schedule).Load();
    		Context.Entry(occurrenceEntity).Reference(e => e.Task).Load();
    		Context.Entry(occurrenceEntity).Reference(e => e.User).Load();
        
        	if (result.Succeeded) {
    			await AfterUpdateAsync(occurrenceEntity);
    			return Ok(new { occurrence = occurrenceEntity.ToDto() });
        	} else {
        		return BadRequest(result);
        	}
    	}
    }
}
