//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Altask.www.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Linq;
    using System.Threading.Tasks;
    using System.Web.Mvc;
    using System.Xml;
    using Altask.www.Models;
    using Data.Model;
    
    [Authorize]
    public partial class ScheduleController : BaseController<Altask.Data.Model.Schedule, Altask.Data.Dto.Schedule>
    {
    	/// <summary>
    	/// Constructor
    	/// </summary>
    	public ScheduleController() : base() {
    	
    	}
    
    	/// <summary>
    	/// Constructor
    	/// </summary>
    	/// <param name="userManager">The application user manager used in this application. UserManager is defined in ASP.NET Identity and is used by the application.</param>
    	/// <param name="signInManager">The application sign-in manager which is used in this application.</param>
    	public ScheduleController(ApplicationUserManager userManager, ApplicationSignInManager signInManager) : base(userManager, signInManager) {
    
    	}
    
    	[HttpPost]
    	[JsonNetFilter]
    	/// <summary>
    	/// Create a <see cref="Altask.Data.Model.Schedule"/>.
    	/// </summary>
    	/// <param name="schedule"></param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> Create(Altask.Data.Dto.Schedule schedule) {
    		ThrowIfDisposed();
    
    		if (!ModelState.IsValid) {
    			return BadRequest(ModelState);
    		}
    
    		var newSchedule = new Altask.Data.Model.Schedule().FromDto(schedule);
    		Context.Schedules.Add(newSchedule);
    		BeforeCreate(newSchedule, schedule);
    		var result = await Context.SaveChangesAsync();
    		Context.Entry(newSchedule).Collection(e => e.Assets).Load();
    		Context.Entry(newSchedule).Collection(e => e.Users).Load();
        
        	if (result.Succeeded) {
    			await AfterCreateAsync(newSchedule);
    			return Ok(new { schedule = newSchedule.ToDto() });
        	} else {
        		return BadRequest(result);
        	}
    	}
    
    	[HttpGet]
    	[JsonNetFilter]
    	/// <summary>
    	/// Returns a <see cref="Altask.Data.Model.Schedule"/> having the specified ID.
    	/// </summary>
    	/// <param name="id">The ID of the <see cref="Altask.Data.Model.Schedule"/>.</param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> FindById(long id) {
    		ThrowIfDisposed();
    		var schedule = await Context.Schedules.FindAsync(id);
    		return Ok(new { schedule = schedule.ToDto() }, JsonRequestBehavior.AllowGet);
    	}
    
    	[HttpGet]
    	[JsonNetFilter]
    	/// <summary>
    	/// Returns a collection of <see cref="Altask.Data.Model.Schedule"/> objects matching the specified filter.
    	/// </summary>
    	/// <param name="filter">A <see cref="Altask.www.Models.ScheduleListOptions"/> object on which to filter.</param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> List(ScheduleListOptions filter) {
    		ThrowIfDisposed();
    
    		if (filter == null) {
    			filter = new ScheduleListOptions();
    		}
    
    		var dtoSchedules = new List<Altask.Data.Dto.Schedule>();
    		var schedule = await Context.Schedules.AsNoTracking().Where(filter.GetPredicate())
    			.Include(e => e.Assets)
    			.Include(e => e.Users)
    			.ToListAsync();
    
    		foreach(var item in schedule) {
    			dtoSchedules.Add(item.ToDto());
    		}
    
    		return Ok(new { schedules = dtoSchedules }, JsonRequestBehavior.AllowGet);
    	}
    
    	[HttpPost]
    	[JsonNetFilter]
    	/// <summary>
    	/// Updates the specified <see cref="Altask.Data.Model.Schedule"/>.
    	/// </summary>
    	/// <param name="schedule"></param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> Update(Altask.Data.Dto.Schedule schedule) {
    		ThrowIfDisposed();
    
    		if (!ModelState.IsValid) {
    			return BadRequest(ModelState);
    		}
    
    		var scheduleEntity = await Context.Schedules.FindAsync(schedule.Id);
    
    		if (scheduleEntity == null) {
    			return BadRequest(ErrorDescriber.DoesNotExist("Schedule"));
    		}
    
    		scheduleEntity.FromDto(schedule);
    		Context.Entry(scheduleEntity).State = EntityState.Modified;
    		BeforeUpdate(scheduleEntity, schedule);
    		var result = await Context.SaveChangesAsync();
    		Context.Entry(scheduleEntity).Collection(e => e.Assets).Load();
    		Context.Entry(scheduleEntity).Collection(e => e.Users).Load();
        
        	if (result.Succeeded) {
    			await AfterUpdateAsync(scheduleEntity);
    			return Ok(new { schedule = scheduleEntity.ToDto() });
        	} else {
        		return BadRequest(result);
        	}
    	}
    }
}
