//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Altask.www.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Linq;
    using System.Threading.Tasks;
    using System.Web.Mvc;
    using System.Xml;
    using Altask.www.Models;
    using Data.Model;
    
    [Authorize]
    public partial class TaskAlertController : BaseController<Altask.Data.Model.TaskAlert, Altask.Data.Dto.TaskAlert>
    {
    	/// <summary>
    	/// Constructor
    	/// </summary>
    	public TaskAlertController() : base() {
    	
    	}
    
    	/// <summary>
    	/// Constructor
    	/// </summary>
    	/// <param name="userManager">The application user manager used in this application. UserManager is defined in ASP.NET Identity and is used by the application.</param>
    	/// <param name="signInManager">The application sign-in manager which is used in this application.</param>
    	public TaskAlertController(ApplicationUserManager userManager, ApplicationSignInManager signInManager) : base(userManager, signInManager) {
    
    	}
    
    	[HttpPost]
    	[JsonNetFilter]
    	/// <summary>
    	/// Create a <see cref="Altask.Data.Model.TaskAlert"/>.
    	/// </summary>
    	/// <param name="taskAlert"></param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> Create(Altask.Data.Dto.TaskAlert taskAlert) {
    		ThrowIfDisposed();
    
    		if (!ModelState.IsValid) {
    			return BadRequest(ModelState);
    		}
    
    		var newTaskAlert = new Altask.Data.Model.TaskAlert().FromDto(taskAlert);
    		Context.TaskAlerts.Add(newTaskAlert);
    		BeforeCreate(newTaskAlert, taskAlert);
    		var result = await Context.SaveChangesAsync();
    		Context.Entry(newTaskAlert).Collection(e => e.Users).Load();
        
        	if (result.Succeeded) {
    			await AfterCreateAsync(newTaskAlert);
    			return Ok(new { taskAlert = newTaskAlert.ToDto() });
        	} else {
        		return BadRequest(result);
        	}
    	}
    
    	[HttpGet]
    	[JsonNetFilter]
    	/// <summary>
    	/// Returns a <see cref="Altask.Data.Model.TaskAlert"/> having the specified ID.
    	/// </summary>
    	/// <param name="id">The ID of the <see cref="Altask.Data.Model.TaskAlert"/>.</param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> FindById(long id) {
    		ThrowIfDisposed();
    		var taskAlert = await Context.TaskAlerts.FindAsync(id);
    		return Ok(new { taskAlert = taskAlert.ToDto() }, JsonRequestBehavior.AllowGet);
    	}
    
    	[HttpGet]
    	[JsonNetFilter]
    	/// <summary>
    	/// Returns a collection of <see cref="Altask.Data.Model.TaskAlert"/> objects matching the specified filter.
    	/// </summary>
    	/// <param name="filter">A <see cref="Altask.www.Models.TaskAlertListOptions"/> object on which to filter.</param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> List(TaskAlertListOptions filter) {
    		ThrowIfDisposed();
    
    		if (filter == null) {
    			filter = new TaskAlertListOptions();
    		}
    
    		var dtoTaskAlerts = new List<Altask.Data.Dto.TaskAlert>();
    		var taskAlert = await Context.TaskAlerts.AsNoTracking().Where(filter.GetPredicate())
    			.Include(e => e.Users)
    			.ToListAsync();
    
    		foreach(var item in taskAlert) {
    			dtoTaskAlerts.Add(item.ToDto());
    		}
    
    		return Ok(new { taskAlerts = dtoTaskAlerts }, JsonRequestBehavior.AllowGet);
    	}
    
    	[HttpPost]
    	[JsonNetFilter]
    	/// <summary>
    	/// Updates the specified <see cref="Altask.Data.Model.TaskAlert"/>.
    	/// </summary>
    	/// <param name="taskAlert"></param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> Update(Altask.Data.Dto.TaskAlert taskAlert) {
    		ThrowIfDisposed();
    
    		if (!ModelState.IsValid) {
    			return BadRequest(ModelState);
    		}
    
    		var taskAlertEntity = await Context.TaskAlerts.FindAsync(taskAlert.Id);
    
    		if (taskAlertEntity == null) {
    			return BadRequest(ErrorDescriber.DoesNotExist("TaskAlert"));
    		}
    
    		taskAlertEntity.FromDto(taskAlert);
    		Context.Entry(taskAlertEntity).State = EntityState.Modified;
    		BeforeUpdate(taskAlertEntity, taskAlert);
    		var result = await Context.SaveChangesAsync();
    		Context.Entry(taskAlertEntity).Collection(e => e.Users).Load();
        
        	if (result.Succeeded) {
    			await AfterUpdateAsync(taskAlertEntity);
    			return Ok(new { taskAlert = taskAlertEntity.ToDto() });
        	} else {
        		return BadRequest(result);
        	}
    	}
    }
}
