//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Altask.www.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Linq;
    using System.Threading.Tasks;
    using System.Web.Mvc;
    using System.Xml;
    using Altask.www.Models;
    using Data.Model;
    
    [Authorize]
    public partial class TaskCategoryController : BaseController<Altask.Data.Model.TaskCategory, Altask.Data.Dto.TaskCategory>
    {
    	/// <summary>
    	/// Constructor
    	/// </summary>
    	public TaskCategoryController() : base() {
    	
    	}
    
    	/// <summary>
    	/// Constructor
    	/// </summary>
    	/// <param name="userManager">The application user manager used in this application. UserManager is defined in ASP.NET Identity and is used by the application.</param>
    	/// <param name="signInManager">The application sign-in manager which is used in this application.</param>
    	public TaskCategoryController(ApplicationUserManager userManager, ApplicationSignInManager signInManager) : base(userManager, signInManager) {
    
    	}
    
    	[HttpPost]
    	[JsonNetFilter]
    	/// <summary>
    	/// Create a <see cref="Altask.Data.Model.TaskCategory"/>.
    	/// </summary>
    	/// <param name="taskCategory"></param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> Create(Altask.Data.Dto.TaskCategory taskCategory) {
    		ThrowIfDisposed();
    
    		if (!ModelState.IsValid) {
    			return BadRequest(ModelState);
    		}
    
    		var newTaskCategory = new Altask.Data.Model.TaskCategory().FromDto(taskCategory);
    		Context.TaskCategories.Add(newTaskCategory);
    		BeforeCreate(newTaskCategory, taskCategory);
    		var result = await Context.SaveChangesAsync();
        
        	if (result.Succeeded) {
    			await AfterCreateAsync(newTaskCategory);
    			return Ok(new { taskCategory = newTaskCategory.ToDto() });
        	} else {
        		return BadRequest(result);
        	}
    	}
    
    	[HttpGet]
    	[JsonNetFilter]
    	/// <summary>
    	/// Returns a <see cref="Altask.Data.Model.TaskCategory"/> having the specified ID.
    	/// </summary>
    	/// <param name="id">The ID of the <see cref="Altask.Data.Model.TaskCategory"/>.</param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> FindById(int id) {
    		ThrowIfDisposed();
    		var taskCategory = await Context.TaskCategories.FindAsync(id);
    		return Ok(new { taskCategory = taskCategory.ToDto() }, JsonRequestBehavior.AllowGet);
    	}
    
    	[HttpGet]
    	[JsonNetFilter]
    	/// <summary>
    	/// Returns a collection of <see cref="Altask.Data.Model.TaskCategory"/> objects matching the specified filter.
    	/// </summary>
    	/// <param name="filter">A <see cref="Altask.www.Models.TaskCategoryListOptions"/> object on which to filter.</param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> List(TaskCategoryListOptions filter) {
    		ThrowIfDisposed();
    
    		if (filter == null) {
    			filter = new TaskCategoryListOptions();
    		}
    
    		var dtoTaskCategories = new List<Altask.Data.Dto.TaskCategory>();
    		var taskCategory = await Context.TaskCategories.AsNoTracking().Where(filter.GetPredicate())
    			.ToListAsync();
    
    		foreach(var item in taskCategory) {
    			dtoTaskCategories.Add(item.ToDto());
    		}
    
    		return Ok(new { taskCategories = dtoTaskCategories }, JsonRequestBehavior.AllowGet);
    	}
    
    	[HttpPost]
    	[JsonNetFilter]
    	/// <summary>
    	/// Updates the specified <see cref="Altask.Data.Model.TaskCategory"/>.
    	/// </summary>
    	/// <param name="taskCategory"></param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> Update(Altask.Data.Dto.TaskCategory taskCategory) {
    		ThrowIfDisposed();
    
    		if (!ModelState.IsValid) {
    			return BadRequest(ModelState);
    		}
    
    		var taskCategoryEntity = await Context.TaskCategories.FindAsync(taskCategory.Id);
    
    		if (taskCategoryEntity == null) {
    			return BadRequest(ErrorDescriber.DoesNotExist("TaskCategory"));
    		}
    
    		taskCategoryEntity.FromDto(taskCategory);
    		Context.Entry(taskCategoryEntity).State = EntityState.Modified;
    		BeforeUpdate(taskCategoryEntity, taskCategory);
    		var result = await Context.SaveChangesAsync();
        
        	if (result.Succeeded) {
    			await AfterUpdateAsync(taskCategoryEntity);
    			return Ok(new { taskCategory = taskCategoryEntity.ToDto() });
        	} else {
        		return BadRequest(result);
        	}
    	}
    }
}
