//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Altask.www.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Linq;
    using System.Threading.Tasks;
    using System.Web.Mvc;
    using System.Xml;
    using Altask.www.Models;
    using Data.Model;
    
    [Authorize]
    public partial class TaskTypeController : BaseController<Altask.Data.Model.TaskType, Altask.Data.Dto.TaskType>
    {
    	/// <summary>
    	/// Constructor
    	/// </summary>
    	public TaskTypeController() : base() {
    	
    	}
    
    	/// <summary>
    	/// Constructor
    	/// </summary>
    	/// <param name="userManager">The application user manager used in this application. UserManager is defined in ASP.NET Identity and is used by the application.</param>
    	/// <param name="signInManager">The application sign-in manager which is used in this application.</param>
    	public TaskTypeController(ApplicationUserManager userManager, ApplicationSignInManager signInManager) : base(userManager, signInManager) {
    
    	}
    
    	[HttpPost]
    	[JsonNetFilter]
    	/// <summary>
    	/// Create a <see cref="Altask.Data.Model.TaskType"/>.
    	/// </summary>
    	/// <param name="taskType"></param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> Create(Altask.Data.Dto.TaskType taskType) {
    		ThrowIfDisposed();
    
    		if (!ModelState.IsValid) {
    			return BadRequest(ModelState);
    		}
    
    		var newTaskType = new Altask.Data.Model.TaskType().FromDto(taskType);
    		Context.TaskTypes.Add(newTaskType);
    		BeforeCreate(newTaskType, taskType);
    		var result = await Context.SaveChangesAsync();
        
        	if (result.Succeeded) {
    			await AfterCreateAsync(newTaskType);
    			return Ok(new { taskType = newTaskType.ToDto() });
        	} else {
        		return BadRequest(result);
        	}
    	}
    
    	[HttpGet]
    	[JsonNetFilter]
    	/// <summary>
    	/// Returns a <see cref="Altask.Data.Model.TaskType"/> having the specified ID.
    	/// </summary>
    	/// <param name="id">The ID of the <see cref="Altask.Data.Model.TaskType"/>.</param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> FindById(int id) {
    		ThrowIfDisposed();
    		var taskType = await Context.TaskTypes.FindAsync(id);
    		return Ok(new { taskType = taskType.ToDto() }, JsonRequestBehavior.AllowGet);
    	}
    
    	[HttpGet]
    	[JsonNetFilter]
    	/// <summary>
    	/// Returns a collection of <see cref="Altask.Data.Model.TaskType"/> objects matching the specified filter.
    	/// </summary>
    	/// <param name="filter">A <see cref="Altask.www.Models.TaskTypeListOptions"/> object on which to filter.</param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> List(TaskTypeListOptions filter) {
    		ThrowIfDisposed();
    
    		if (filter == null) {
    			filter = new TaskTypeListOptions();
    		}
    
    		var dtoTaskTypes = new List<Altask.Data.Dto.TaskType>();
    		var taskType = await Context.TaskTypes.AsNoTracking().Where(filter.GetPredicate())
    			.ToListAsync();
    
    		foreach(var item in taskType) {
    			dtoTaskTypes.Add(item.ToDto());
    		}
    
    		return Ok(new { taskTypes = dtoTaskTypes }, JsonRequestBehavior.AllowGet);
    	}
    
    	[HttpPost]
    	[JsonNetFilter]
    	/// <summary>
    	/// Updates the specified <see cref="Altask.Data.Model.TaskType"/>.
    	/// </summary>
    	/// <param name="taskType"></param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> Update(Altask.Data.Dto.TaskType taskType) {
    		ThrowIfDisposed();
    
    		if (!ModelState.IsValid) {
    			return BadRequest(ModelState);
    		}
    
    		var taskTypeEntity = await Context.TaskTypes.FindAsync(taskType.Id);
    
    		if (taskTypeEntity == null) {
    			return BadRequest(ErrorDescriber.DoesNotExist("TaskType"));
    		}
    
    		taskTypeEntity.FromDto(taskType);
    		Context.Entry(taskTypeEntity).State = EntityState.Modified;
    		BeforeUpdate(taskTypeEntity, taskType);
    		var result = await Context.SaveChangesAsync();
        
        	if (result.Succeeded) {
    			await AfterUpdateAsync(taskTypeEntity);
    			return Ok(new { taskType = taskTypeEntity.ToDto() });
        	} else {
        		return BadRequest(result);
        	}
    	}
    }
}
