//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Altask.www.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Linq;
    using System.Threading.Tasks;
    using System.Web.Mvc;
    using System.Xml;
    using Altask.www.Models;
    using Data.Model;
    
    [Authorize]
    public partial class UserRoleController : BaseController<Altask.Data.Model.UserRole, Altask.Data.Dto.UserRole>
    {
    	/// <summary>
    	/// Constructor
    	/// </summary>
    	public UserRoleController() : base() {
    	
    	}
    
    	/// <summary>
    	/// Constructor
    	/// </summary>
    	/// <param name="userManager">The application user manager used in this application. UserManager is defined in ASP.NET Identity and is used by the application.</param>
    	/// <param name="signInManager">The application sign-in manager which is used in this application.</param>
    	public UserRoleController(ApplicationUserManager userManager, ApplicationSignInManager signInManager) : base(userManager, signInManager) {
    
    	}
    
    	[HttpPost]
    	[JsonNetFilter]
    	/// <summary>
    	/// Create a <see cref="Altask.Data.Model.UserRole"/>.
    	/// </summary>
    	/// <param name="userRole"></param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> Create(Altask.Data.Dto.UserRole userRole) {
    		ThrowIfDisposed();
    
    		if (!ModelState.IsValid) {
    			return BadRequest(ModelState);
    		}
    
    		var newUserRole = new Altask.Data.Model.UserRole().FromDto(userRole);
    		Context.UserRoles.Add(newUserRole);
    		BeforeCreate(newUserRole, userRole);
    		var result = await Context.SaveChangesAsync();
    		Context.Entry(newUserRole).Reference(e => e.Role).Load();
        
        	if (result.Succeeded) {
    			await AfterCreateAsync(newUserRole);
    			return Ok(new { userRole = newUserRole.ToDto() });
        	} else {
        		return BadRequest(result);
        	}
    	}
    
    	[HttpGet]
    	[JsonNetFilter]
    	/// <summary>
    	/// Returns a <see cref="Altask.Data.Model.UserRole"/> having the specified ID.
    	/// </summary>
    	/// <param name="id">The ID of the <see cref="Altask.Data.Model.UserRole"/>.</param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> FindById(int id) {
    		ThrowIfDisposed();
    		var userRole = await Context.UserRoles.FindAsync(id);
    		return Ok(new { userRole = userRole.ToDto() }, JsonRequestBehavior.AllowGet);
    	}
    
    	[HttpGet]
    	[JsonNetFilter]
    	/// <summary>
    	/// Returns a collection of <see cref="Altask.Data.Model.UserRole"/> objects matching the specified filter.
    	/// </summary>
    	/// <param name="filter">A <see cref="Altask.www.Models.UserRoleListOptions"/> object on which to filter.</param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> List(UserRoleListOptions filter) {
    		ThrowIfDisposed();
    
    		if (filter == null) {
    			filter = new UserRoleListOptions();
    		}
    
    		var dtoUserRoles = new List<Altask.Data.Dto.UserRole>();
    		var userRole = await Context.UserRoles.AsNoTracking().Where(filter.GetPredicate())
    			.Include(e => e.Role)
    			.ToListAsync();
    
    		foreach(var item in userRole) {
    			dtoUserRoles.Add(item.ToDto());
    		}
    
    		return Ok(new { userRoles = dtoUserRoles }, JsonRequestBehavior.AllowGet);
    	}
    
    	[HttpPost]
    	[JsonNetFilter]
    	/// <summary>
    	/// Updates the specified <see cref="Altask.Data.Model.UserRole"/>.
    	/// </summary>
    	/// <param name="userRole"></param>
    	/// <returns>Returns a <see cref="Altask.Data.EntityResult"/> indicating success or failure.</returns>
    	public virtual async Task<ActionResult> Update(Altask.Data.Dto.UserRole userRole) {
    		ThrowIfDisposed();
    
    		if (!ModelState.IsValid) {
    			return BadRequest(ModelState);
    		}
    
    		var userRoleEntity = await Context.UserRoles.FindAsync(userRole.Id);
    
    		if (userRoleEntity == null) {
    			return BadRequest(ErrorDescriber.DoesNotExist("UserRole"));
    		}
    
    		userRoleEntity.FromDto(userRole);
    		Context.Entry(userRoleEntity).State = EntityState.Modified;
    		BeforeUpdate(userRoleEntity, userRole);
    		var result = await Context.SaveChangesAsync();
    		Context.Entry(userRoleEntity).Reference(e => e.Role).Load();
        
        	if (result.Succeeded) {
    			await AfterUpdateAsync(userRoleEntity);
    			return Ok(new { userRole = userRoleEntity.ToDto() });
        	} else {
        		return BadRequest(result);
        	}
    	}
    }
}
