//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Altask.www.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    /// <summary>
    ///	Represents a collection of properties on which you can filter a collection of <see cref="Altask.Data.Dto.AssetGrouping"/> objects.
    /// </summary>
    public partial class AssetGroupingListOptions : ListOptions<Altask.Data.Model.AssetGrouping>
    {
    	/// <summary>
    	///	A comma delimited string representing one or more <see cref="Altask.Data.Dto.AssetGrouping"/>.AssetGroupId values to filter on.
    	/// </summary>
    	public string AssetGroupIds { get; set; }
    
    	/// <summary>
    	///	Parses the AssetGroupIds property and returns a <see cref="System.Collections.Generic.List{Int32}"/> containing any <see cref="Altask.Data.Dto.AssetGrouping"/>.AssetGroupId values to filter on.
    	/// </summary>
    	public List<Int32> GetAssetGroupIds() {
    		var list = new List<Int32>();
    		
    		if (AssetGroupIds != null) {
    			var items = AssetGroupIds.Split(',');
    
    			foreach(var item in items) {
    				Int32 parsed;
    
    				if (Int32.TryParse(item, out parsed)) {
    					list.Add(parsed);
    				}
    			}
    		}
    
    		return list;
    	}
    
    	/// <summary>
    	///	Creates a Predicate derived from the filter's AssetGroupIds property.
    	/// </summary>
    	private Expression<Func<Altask.Data.Model.AssetGrouping, bool>> GetAssetGroupIdsPredicate() {
    		var values = GetAssetGroupIds();
    
    		if (values.Count > 0) {
    			var predicate = PredicateBuilder.False<Altask.Data.Model.AssetGrouping>();
    
    			foreach(var item in values) {
    				var value = item;
    				predicate = predicate.Or(e => e.AssetGroupId == value);
    			}
    
    			return predicate;
    		}
    		
    		return null;	
    	}
    
    	/// <summary>
    	///	Creates a Predicate from the filter's specified properties which evaluates to true.
    	/// </summary>
    	public Expression<Func<Altask.Data.Model.AssetGrouping, bool>> GetPredicate() {
    		var predicate = PredicateBuilder.True<Altask.Data.Model.AssetGrouping>();
    		var custom = GetCustomPredicate();
    
            if (custom != null) {
                predicate = predicate.And(custom);
            }
    
    		var assetGroupIdsPredicate = GetAssetGroupIdsPredicate();
    
    		if (assetGroupIdsPredicate != null) {
    			predicate = predicate.And(assetGroupIdsPredicate);
    		}
    
    		return predicate;	
    	}
    }
}
