//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Altask.www.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    /// <summary>
    ///	Represents a collection of properties on which you can filter a collection of <see cref="Altask.Data.Dto.Asset"/> objects.
    /// </summary>
    public partial class AssetListOptions : ListOptions<Altask.Data.Model.Asset>
    {
    	/// <summary>
    	/// Indicates wheather to filter on the <see cref="Altask.Data.Dto.Asset"/>.Active property.
    	/// </summary>
    	public bool? Active { get; set; }
    
    	/// <summary>
    	///	Creates a Predicate derived from the filter's Active property.
    	/// </summary>
    	private Expression<Func<Altask.Data.Model.Asset, bool>> GetActivePredicate() {
    		if (Active.HasValue) {
    			var predicate = PredicateBuilder.True<Altask.Data.Model.Asset>();
    			var value = Active.Value;
    			predicate = predicate.And(e => e.Active == value);
    			return predicate;
    		}
    		
    		return null;	
    	}
    		
    	/// <summary>
    	///	A comma delimited string representing one or more <see cref="Altask.Data.Dto.Asset"/>.AssetTypeId values to filter on.
    	/// </summary>
    	public string AssetTypeIds { get; set; }
    
    	/// <summary>
    	///	Parses the AssetTypeIds property and returns a <see cref="System.Collections.Generic.List{Int32}"/> containing any <see cref="Altask.Data.Dto.Asset"/>.AssetTypeId values to filter on.
    	/// </summary>
    	public List<Int32> GetAssetTypeIds() {
    		var list = new List<Int32>();
    		
    		if (AssetTypeIds != null) {
    			var items = AssetTypeIds.Split(',');
    
    			foreach(var item in items) {
    				Int32 parsed;
    
    				if (Int32.TryParse(item, out parsed)) {
    					list.Add(parsed);
    				}
    			}
    		}
    
    		return list;
    	}
    
    	/// <summary>
    	///	Creates a Predicate derived from the filter's AssetTypeIds property.
    	/// </summary>
    	private Expression<Func<Altask.Data.Model.Asset, bool>> GetAssetTypeIdsPredicate() {
    		var values = GetAssetTypeIds();
    
    		if (values.Count > 0) {
    			var predicate = PredicateBuilder.False<Altask.Data.Model.Asset>();
    
    			foreach(var item in values) {
    				var value = item;
    				predicate = predicate.Or(e => e.AssetTypeId == value);
    			}
    
    			return predicate;
    		}
    		
    		return null;	
    	}
    
    	/// <summary>
    	///	A comma delimited string representing one or more <see cref="Altask.Data.Dto.Asset"/>.DepartmentId values to filter on.
    	/// </summary>
    	public string DepartmentIds { get; set; }
    
    	/// <summary>
    	///	Parses the DepartmentIds property and returns a <see cref="System.Collections.Generic.List{Int32}"/> containing any <see cref="Altask.Data.Dto.Asset"/>.DepartmentId values to filter on.
    	/// </summary>
    	public List<Int32> GetDepartmentIds() {
    		var list = new List<Int32>();
    		
    		if (DepartmentIds != null) {
    			var items = DepartmentIds.Split(',');
    
    			foreach(var item in items) {
    				Int32 parsed;
    
    				if (Int32.TryParse(item, out parsed)) {
    					list.Add(parsed);
    				}
    			}
    		}
    
    		return list;
    	}
    
    	/// <summary>
    	///	Creates a Predicate derived from the filter's DepartmentIds property.
    	/// </summary>
    	private Expression<Func<Altask.Data.Model.Asset, bool>> GetDepartmentIdsPredicate() {
    		var values = GetDepartmentIds();
    
    		if (values.Count > 0) {
    			var predicate = PredicateBuilder.False<Altask.Data.Model.Asset>();
    
    			foreach(var item in values) {
    				var value = item;
    				predicate = predicate.Or(e => e.DepartmentId == value);
    			}
    
    			return predicate;
    		}
    		
    		return null;	
    	}
    
    	/// <summary>
    	///	A comma delimited string representing one or more <see cref="Altask.Data.Dto.Asset"/>.ManufacturerId values to filter on.
    	/// </summary>
    	public string ManufacturerIds { get; set; }
    
    	/// <summary>
    	///	Parses the ManufacturerIds property and returns a <see cref="System.Collections.Generic.List{Int32}"/> containing any <see cref="Altask.Data.Dto.Asset"/>.ManufacturerId values to filter on.
    	/// </summary>
    	public List<Int32> GetManufacturerIds() {
    		var list = new List<Int32>();
    		
    		if (ManufacturerIds != null) {
    			var items = ManufacturerIds.Split(',');
    
    			foreach(var item in items) {
    				Int32 parsed;
    
    				if (Int32.TryParse(item, out parsed)) {
    					list.Add(parsed);
    				}
    			}
    		}
    
    		return list;
    	}
    
    	/// <summary>
    	///	Creates a Predicate derived from the filter's ManufacturerIds property.
    	/// </summary>
    	private Expression<Func<Altask.Data.Model.Asset, bool>> GetManufacturerIdsPredicate() {
    		var values = GetManufacturerIds();
    
    		if (values.Count > 0) {
    			var predicate = PredicateBuilder.False<Altask.Data.Model.Asset>();
    
    			foreach(var item in values) {
    				var value = item;
    				predicate = predicate.Or(e => e.ManufacturerId == value);
    			}
    
    			return predicate;
    		}
    		
    		return null;	
    	}
    
    	/// <summary>
    	///	Creates a Predicate from the filter's specified properties which evaluates to true.
    	/// </summary>
    	public Expression<Func<Altask.Data.Model.Asset, bool>> GetPredicate() {
    		var predicate = PredicateBuilder.True<Altask.Data.Model.Asset>();
    		var custom = GetCustomPredicate();
    
            if (custom != null) {
                predicate = predicate.And(custom);
            }
    
    		var activePredicate = GetActivePredicate();
    
    		if (activePredicate != null) {
    			predicate = predicate.And(activePredicate);
    		}
    		var assetTypeIdsPredicate = GetAssetTypeIdsPredicate();
    
    		if (assetTypeIdsPredicate != null) {
    			predicate = predicate.And(assetTypeIdsPredicate);
    		}
    		var departmentIdsPredicate = GetDepartmentIdsPredicate();
    
    		if (departmentIdsPredicate != null) {
    			predicate = predicate.And(departmentIdsPredicate);
    		}
    		var manufacturerIdsPredicate = GetManufacturerIdsPredicate();
    
    		if (manufacturerIdsPredicate != null) {
    			predicate = predicate.And(manufacturerIdsPredicate);
    		}
    
    		return predicate;	
    	}
    }
}
