//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Altask.www.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    /// <summary>
    ///	Represents a collection of properties on which you can filter a collection of <see cref="Altask.Data.Dto.Task"/> objects.
    /// </summary>
    public partial class TaskListOptions : ListOptions<Altask.Data.Model.Task>
    {
    	/// <summary>
    	/// Indicates wheather to filter on the <see cref="Altask.Data.Dto.Task"/>.Active property.
    	/// </summary>
    	public bool? Active { get; set; }
    
    	/// <summary>
    	///	Creates a Predicate derived from the filter's Active property.
    	/// </summary>
    	private Expression<Func<Altask.Data.Model.Task, bool>> GetActivePredicate() {
    		if (Active.HasValue) {
    			var predicate = PredicateBuilder.True<Altask.Data.Model.Task>();
    			var value = Active.Value;
    			predicate = predicate.And(e => e.Active == value);
    			return predicate;
    		}
    		
    		return null;	
    	}
    		
    	/// <summary>
    	///	A comma delimited string representing one or more <see cref="Altask.Data.Dto.Task"/>.FormId values to filter on.
    	/// </summary>
    	public string FormIds { get; set; }
    
    	/// <summary>
    	///	Parses the FormIds property and returns a <see cref="System.Collections.Generic.List{Int32}"/> containing any <see cref="Altask.Data.Dto.Task"/>.FormId values to filter on.
    	/// </summary>
    	public List<Int32> GetFormIds() {
    		var list = new List<Int32>();
    		
    		if (FormIds != null) {
    			var items = FormIds.Split(',');
    
    			foreach(var item in items) {
    				Int32 parsed;
    
    				if (Int32.TryParse(item, out parsed)) {
    					list.Add(parsed);
    				}
    			}
    		}
    
    		return list;
    	}
    
    	/// <summary>
    	///	Creates a Predicate derived from the filter's FormIds property.
    	/// </summary>
    	private Expression<Func<Altask.Data.Model.Task, bool>> GetFormIdsPredicate() {
    		var values = GetFormIds();
    
    		if (values.Count > 0) {
    			var predicate = PredicateBuilder.False<Altask.Data.Model.Task>();
    
    			foreach(var item in values) {
    				var value = item;
    				predicate = predicate.Or(e => e.FormId == value);
    			}
    
    			return predicate;
    		}
    		
    		return null;	
    	}
    
    	/// <summary>
    	///	A comma delimited string representing one or more <see cref="Altask.Data.Dto.Task"/>.TaskCategoryId values to filter on.
    	/// </summary>
    	public string TaskCategoryIds { get; set; }
    
    	/// <summary>
    	///	Parses the TaskCategoryIds property and returns a <see cref="System.Collections.Generic.List{Int32}"/> containing any <see cref="Altask.Data.Dto.Task"/>.TaskCategoryId values to filter on.
    	/// </summary>
    	public List<Int32> GetTaskCategoryIds() {
    		var list = new List<Int32>();
    		
    		if (TaskCategoryIds != null) {
    			var items = TaskCategoryIds.Split(',');
    
    			foreach(var item in items) {
    				Int32 parsed;
    
    				if (Int32.TryParse(item, out parsed)) {
    					list.Add(parsed);
    				}
    			}
    		}
    
    		return list;
    	}
    
    	/// <summary>
    	///	Creates a Predicate derived from the filter's TaskCategoryIds property.
    	/// </summary>
    	private Expression<Func<Altask.Data.Model.Task, bool>> GetTaskCategoryIdsPredicate() {
    		var values = GetTaskCategoryIds();
    
    		if (values.Count > 0) {
    			var predicate = PredicateBuilder.False<Altask.Data.Model.Task>();
    
    			foreach(var item in values) {
    				var value = item;
    				predicate = predicate.Or(e => e.TaskCategoryId == value);
    			}
    
    			return predicate;
    		}
    		
    		return null;	
    	}
    
    	/// <summary>
    	///	A comma delimited string representing one or more <see cref="Altask.Data.Dto.Task"/>.TaskTypeId values to filter on.
    	/// </summary>
    	public string TaskTypeIds { get; set; }
    
    	/// <summary>
    	///	Parses the TaskTypeIds property and returns a <see cref="System.Collections.Generic.List{Int32}"/> containing any <see cref="Altask.Data.Dto.Task"/>.TaskTypeId values to filter on.
    	/// </summary>
    	public List<Int32> GetTaskTypeIds() {
    		var list = new List<Int32>();
    		
    		if (TaskTypeIds != null) {
    			var items = TaskTypeIds.Split(',');
    
    			foreach(var item in items) {
    				Int32 parsed;
    
    				if (Int32.TryParse(item, out parsed)) {
    					list.Add(parsed);
    				}
    			}
    		}
    
    		return list;
    	}
    
    	/// <summary>
    	///	Creates a Predicate derived from the filter's TaskTypeIds property.
    	/// </summary>
    	private Expression<Func<Altask.Data.Model.Task, bool>> GetTaskTypeIdsPredicate() {
    		var values = GetTaskTypeIds();
    
    		if (values.Count > 0) {
    			var predicate = PredicateBuilder.False<Altask.Data.Model.Task>();
    
    			foreach(var item in values) {
    				var value = item;
    				predicate = predicate.Or(e => e.TaskTypeId == value);
    			}
    
    			return predicate;
    		}
    		
    		return null;	
    	}
    
    	/// <summary>
    	///	Creates a Predicate from the filter's specified properties which evaluates to true.
    	/// </summary>
    	public Expression<Func<Altask.Data.Model.Task, bool>> GetPredicate() {
    		var predicate = PredicateBuilder.True<Altask.Data.Model.Task>();
    		var custom = GetCustomPredicate();
    
            if (custom != null) {
                predicate = predicate.And(custom);
            }
    
    		var activePredicate = GetActivePredicate();
    
    		if (activePredicate != null) {
    			predicate = predicate.And(activePredicate);
    		}
    		var formIdsPredicate = GetFormIdsPredicate();
    
    		if (formIdsPredicate != null) {
    			predicate = predicate.And(formIdsPredicate);
    		}
    		var taskCategoryIdsPredicate = GetTaskCategoryIdsPredicate();
    
    		if (taskCategoryIdsPredicate != null) {
    			predicate = predicate.And(taskCategoryIdsPredicate);
    		}
    		var taskTypeIdsPredicate = GetTaskTypeIdsPredicate();
    
    		if (taskTypeIdsPredicate != null) {
    			predicate = predicate.And(taskTypeIdsPredicate);
    		}
    
    		return predicate;	
    	}
    }
}
